import type { WorldCity } from '../types'

export const city: WorldCity = {
  id: 'cairo',
  name: 'Cairo',
  country: 'Egypt',
  continent: 'Africa',
  tagline: 'An ancient Nile region, successive capitals, a living metropolis.',
  center: [31.232, 30.044],
  mapBounds: [30.95, 29.83, 31.55, 30.22],
  historicalBounds: [31.08, 29.94, 31.31, 30.11],
  reconstructionNote: 'The ancient chapter concerns Giza in the wider Cairo region: Cairo itself was founded in 969 CE, millennia after the pyramids. Models are original generic symbols, not architectural replicas. District circles are approximate clusters; airport-inclusive viewing bounds are not governorate borders. The hand-traced Nile is orientation only, not a reconstruction of ancient channels or shorelines. Modern uses individually dated evidence beyond a nominal 2025 timeline endpoint.',
  chapters: [
    {
      year: -2500,
      label: 'Ancient Giza region',
      title: 'A royal landscape before Cairo existed',
      description: 'The pyramids at Giza belong to the Old Kingdom landscape of Memphis, not to the founding of Cairo. Royal tombs, temples, settlements and river connections formed a regional system on the edge of the Nile floodplain. Cairo would be founded more than three millennia later. This chapter therefore moves the camera to Giza rather than placing a fictional ancient city in modern downtown Cairo.',
      life: 'Monument building depended on organised labour, craft skills, food supplies and transport. Settlements and workshops supported the royal landscape; the pyramids were part of a lived region, not isolated objects in an empty desert.',
      changes: ['Royal pyramid complexes transform the Giza plateau into a monumental funerary landscape.', 'Labour, settlements and Nile transport connect the plateau to the Memphite region.'],
      sources: ['cairo-memphis-unesco', 'cairo-khufu-ministry'],
      stats: [
        { label: 'Regional population', value: 'Not reliably known', scope: 'Giza and its supporting settlements; no comparable population total in the cited site documentation', asOf: 'Around 2500 BCE', source: 'cairo-memphis-unesco' },
        { label: 'Great Pyramid original height', value: '146.5 m', scope: 'Khufu\'s pyramid at Giza; original height, not its eroded present height', asOf: 'Fourth Dynasty, third millennium BCE', source: 'cairo-khufu-ministry' },
      ],
      focus: [31.1358, 29.9775],
      spanKm: 1.8,
      density: 0.1,
    },
    {
      year: 642,
      label: 'Fustat',
      title: 'A new capital on the Nile',
      description: 'Following the Arab conquest, Fustat developed as the first capital of Islamic Egypt near the river and older settlements. The Mosque of Amr ibn al-As became its central religious institution in 642. This is not yet Fatimid Cairo, and the present mosque should not be mistaken for its original building. Later Cairo absorbed earlier urban centres rather than beginning on an uninhabited regional canvas.',
      life: 'River trade, military administration, worship and crafts supported the new settlement. Muslim newcomers lived within a region with long-established communities and religious traditions; the metropolitan story includes coexistence, political change and unequal power.',
      changes: ['Fustat becomes the administrative centre of Islamic Egypt after the conquest.', 'The Mosque of Amr ibn al-As anchors a new urban and religious focus.'],
      sources: ['cairo-amr-ministry', 'cairo-historic-unesco'],
      stats: [
        { label: 'Population', value: 'Not reliably known', scope: 'Early Fustat; no securely comparable citywide count in the cited sources', asOf: '642 CE', source: 'cairo-amr-ministry' },
        { label: 'Religious institution', value: 'Egypt\'s first mosque', scope: 'Mosque of Amr ibn al-As at Fustat; establishment, not the age of its current fabric', asOf: '642 CE', source: 'cairo-amr-ministry' },
      ],
      focus: [31.234, 30.006],
      spanKm: 4,
      density: 0.2,
    },
    {
      year: 969,
      label: 'Fatimid Cairo',
      title: 'Al-Qahira joins a region of older capitals',
      description: 'The Fatimids founded Cairo, al-Qahira, in 969 as their new headquarters. Its planned nucleus lay north of Fustat and other earlier administrative settlements. Al-Azhar followed as an important Fatimid institution, but does not appear as a completed building at the instant of foundation. The eventual metropolis grew by linking and absorbing these different centres, with their distinct political and religious histories.',
      life: 'Administration, trade and religious patronage connected the new court city to older markets and settlements. Streets and neighbourhoods developed their own identities; the new capital did not replace the region\'s existing communities overnight.',
      changes: ['A new Fatimid political nucleus is founded north of the earlier settlements.', 'An older regional network remains active around the new city rather than disappearing.'],
      sources: ['cairo-historic-unesco', 'cairo-fatimids-ministry'],
      stats: [
        { label: 'Population', value: 'Not reliably known', scope: 'Newly founded Fatimid Cairo; not the combined later metropolis', asOf: '969 CE', source: 'cairo-historic-unesco' },
        { label: 'Earlier capital settlements', value: '3', scope: 'Fustat, al-Askar and al-Qata\'i, identified alongside Fatimid Cairo in UNESCO\'s urban history', asOf: 'Existing before the foundation of Cairo in 969', source: 'cairo-historic-unesco' },
      ],
      focus: [31.262, 30.05],
      spanKm: 4,
      density: 0.35,
    },
    {
      year: 1363,
      label: 'Mamluk metropolis',
      title: 'Institutions extend beyond the old walls',
      description: 'Under the Mamluks, Cairo\'s urban fabric expanded beyond the Fatimid nucleus to connect older settlements and the Citadel. Monumental religious and educational complexes expressed rulers\' authority while supporting learning and public life. Sultan Hassan\'s mosque and madrasa exemplify this institutional landscape. The skyline was accumulated over generations; the much later Muhammad Ali Mosque is deliberately absent from this chapter.',
      life: 'Craft streets, markets, religious schools and endowed services gave neighbourhoods distinctive functions. Monumental patronage and everyday commerce were closely connected, although the benefits and burdens of the imperial capital were unevenly shared.',
      changes: ['Urban growth links the Fatimid core with older settlements and the Citadel.', 'Large mosque-madrasa complexes make education and religious patronage prominent in the cityscape.'],
      sources: ['cairo-historic-unesco', 'cairo-sultan-hassan-ministry'],
      stats: [
        { label: 'Population', value: 'Not reliably known', scope: 'Mamluk Cairo; historical totals are uncertain and no single count is adopted here', asOf: 'Mid-fourteenth century', source: 'cairo-historic-unesco' },
        { label: 'Schools of jurisprudence', value: '4', scope: 'Four Sunni legal schools represented by Sultan Hassan\'s madrasas', asOf: 'Complex built from 1356 into the early 1360s', source: 'cairo-sultan-hassan-ministry' },
      ],
      focus: [31.26, 30.033],
      spanKm: 5,
      density: 0.6,
    },
    {
      year: 1869,
      label: 'Nineteenth-century Cairo',
      title: 'A new city beside the historic fabric',
      description: 'Nineteenth-century development added new urban forms beside the older city rather than simply replacing it. The Muhammad Ali dynasty reshaped government and monumental patronage, including the mosque dominating the Citadel. New districts and European architectural influences widened Cairo\'s visual vocabulary. UNESCO notes that building a new Cairo helped older neighbourhoods survive, although surviving monuments alone cannot describe every resident\'s experience of change.',
      life: 'Older craft and commercial streets continued alongside new administrative and residential districts. People navigated overlapping urban worlds, where changing government priorities and imported architectural fashions met long-established institutions and neighbourhood routines.',
      changes: ['New districts grow beside, rather than entirely over, the medieval urban fabric.', 'Muhammad Ali\'s Citadel mosque adds a nineteenth-century layer to an older seat of power.'],
      sources: ['cairo-historic-unesco', 'cairo-muhammad-ali-ministry'],
      stats: [
        { label: 'Population', value: 'Not reliably known', scope: 'Cairo at the 1869 snapshot; these architectural sources provide no comparable census benchmark', asOf: '1869', source: 'cairo-historic-unesco' },
        { label: 'Mosque building campaign', value: 'About 18 years', scope: 'Muhammad Ali Mosque; 1830-1848 campaign, with completion work under Abbas', asOf: '1830-1848', source: 'cairo-muhammad-ali-ministry' },
      ],
      focus: [31.244, 30.044],
      spanKm: 7,
      density: 0.65,
    },
    {
      year: 2025,
      label: 'Modern - latest dated evidence',
      title: 'A metropolitan region with several histories',
      description: 'Modern Cairo extends across a much wider region than the Fatimid city, while Giza retains its own geography and administrative identity. Museums, transport corridors and riverfront landmarks coexist with living historic neighbourhoods. This endpoint is a modern view, not a claim that all data describe 2025. The population benchmark is the 2017 Cairo governorate census, carefully distinguished from the larger Greater Cairo metropolitan region.',
      life: 'Daily journeys link homes, employment and services across old and new districts. Historic Cairo remains a lived environment, not only a visitor destination; conservation must contend with urban pressures and the needs of existing communities.',
      changes: ['Metropolitan connections bring the airport, Giza and newer districts into a wider viewing area.', 'Heritage conservation addresses living neighbourhoods as well as individual monuments.'],
      sources: ['cairo-population-un', 'cairo-historic-unesco', 'cairo-tower-tourism'],
      stats: [
        { label: 'Census population', value: '9,539,673', scope: 'Cairo urban governorate; UN table footnote specifies governorates, despite its generic agglomeration label. Not Greater Cairo.', asOf: '2017 census; final figure reported in 2018', source: 'cairo-population-un' },
        { label: 'Cairo Tower height', value: '187 m', scope: 'Tower on Gezira Island', asOf: 'Completed in 1961', source: 'cairo-tower-tourism' },
      ],
      focus: [31.226, 30.047],
      spanKm: 12,
      density: 1,
    },
  ],
  places: [
    { id: 'cairo-khufu', name: 'Great Pyramid of Khufu', coordinates: [31.1342, 29.9792], visibleFrom: -2500, model: 'pyramid', dateLabel: 'Fourth Dynasty; already standing by about 2500 BCE', description: 'The Giza pyramid belongs to the Memphite royal landscape and predates Cairo by millennia.', caveat: 'Generic pyramid, not a block-by-block replica. The date is an approximate ancient chronology; Giza is a regional anchor, not the site of Cairo\'s foundation.', sources: ['cairo-khufu-ministry', 'cairo-memphis-unesco'] },
    { id: 'cairo-sphinx', name: 'Great Sphinx and Giza precinct', coordinates: [31.1376, 29.9753], visibleFrom: -2500, model: 'district', dateLabel: 'Old Kingdom Giza complex', description: 'The Sphinx is part of a larger landscape of royal tombs, temples and supporting settlements.', caveat: 'Precinct symbol, not a replica or a proposed original appearance of the Sphinx; ancient dating is approximate.', sources: ['cairo-memphis-unesco'] },
    { id: 'cairo-fustat', name: 'Fustat and Amr mosque site', coordinates: [31.2335, 30.01], visibleFrom: 642, model: 'district', dateLabel: 'Mosque established 642; many later rebuildings', description: 'The first mosque in Egypt marks the early Islamic capital south of the later Fatimid city.', caveat: 'Site-area marker only. None of the present mosque is asserted to be the unchanged structure of 642.', sources: ['cairo-amr-ministry', 'cairo-historic-unesco'] },
    { id: 'cairo-ibn-tulun', name: 'Ibn Tulun Mosque', coordinates: [31.2494, 30.0287], visibleFrom: 879, model: 'temple', dateLabel: 'Built 876-879', description: 'The mosque preserves an important monumental connection to al-Qata\'i, one of Cairo\'s predecessor capitals.', caveat: 'Generic courtyard religious symbol; not an architectural replica, and later alterations are not individually reconstructed.', sources: ['cairo-historic-unesco'] },
    { id: 'cairo-fatimid-core', name: 'Fatimid city and al-Muizz axis', coordinates: [31.2621, 30.05], visibleFrom: 969, model: 'district', dateLabel: 'City founded 969; accumulated later fabric', description: 'A new Fatimid nucleus introduced the street framework around which later historic Cairo developed.', caveat: 'Approximate district marker. Surviving gates, shops and mosques were built at different later dates and are not all backdated to 969.', sources: ['cairo-historic-unesco', 'cairo-fatimids-ministry'] },
    { id: 'cairo-citadel', name: 'Citadel precinct', coordinates: [31.2619, 30.0287], visibleFrom: 1176, model: 'district', dateLabel: 'Citadel established from 1176', description: 'The elevated seat of government became a major political anchor outside the Fatimid nucleus.', caveat: 'Precinct marker rather than a complete medieval fortress model. The nineteenth-century Muhammad Ali Mosque appears separately at its later date.', sources: ['cairo-historic-unesco'] },
    { id: 'cairo-sultan-hassan', name: 'Sultan Hassan mosque and madrasa', coordinates: [31.2564, 30.032], visibleFrom: 1363, model: 'temple', dateLabel: 'Built from 1356 into the early 1360s', description: 'A monumental complex combines worship with teaching for the four Sunni schools of jurisprudence.', caveat: 'Generic religious-school miniature, not a replica. Sources vary in converting the completion date; the finished-complex marker is conservatively gated to 1363.', sources: ['cairo-sultan-hassan-ministry'] },
    { id: 'cairo-muhammad-ali', name: 'Muhammad Ali Mosque', coordinates: [31.2599, 30.0287], visibleFrom: 1848, model: 'dome', dateLabel: 'Main campaign 1830-1848; later completion work', description: 'The domed mosque gives the older Citadel a distinctly nineteenth-century skyline.', caveat: 'Generic dome composition. It is not a medieval Citadel building, and the gate indicates the end of the main campaign rather than every finishing detail.', sources: ['cairo-muhammad-ali-ministry'] },
    { id: 'cairo-egyptian-museum', name: 'Egyptian Museum at Tahrir', coordinates: [31.2336, 30.0478], visibleFrom: 1902, model: 'palace', dateLabel: 'Opened 15 November 1902', description: 'The purpose-built museum added a modern institution for interpreting Egypt\'s antiquities in central Cairo.', caveat: 'Generic civic-building symbol, not a palace or architectural replica. The collection is older than this building; this is not the Grand Egyptian Museum at Giza.', sources: ['cairo-egyptian-museum-ministry'] },
    { id: 'cairo-tower', name: 'Cairo Tower', coordinates: [31.2243, 30.0459], visibleFrom: 1961, model: 'tower', dateLabel: 'Completed 1961', description: 'The 187-metre tower on Gezira adds a modern vertical landmark to the Nile corridor.', caveat: 'Original generic tower symbol; the real lattice design is not reproduced.', sources: ['cairo-tower-tourism'] },
  ],
  water: [
    { name: 'Nile - schematic main channel', kind: 'river', widthKm: 0.48, points: [[31.257, 29.9], [31.245, 29.93], [31.235, 29.955], [31.222, 29.98], [31.218, 30.002], [31.222, 30.022], [31.229, 30.041], [31.227, 30.053], [31.228, 30.069], [31.236, 30.089], [31.234, 30.113], [31.218, 30.143]] },
    { name: 'Nile west of Gezira - schematic branch', kind: 'river', widthKm: 0.16, points: [[31.229, 30.041], [31.219, 30.043], [31.214, 30.049], [31.212, 30.057], [31.213, 30.063], [31.218, 30.068], [31.224, 30.071], [31.228, 30.069]] },
  ],
  districts: [
    { name: 'Giza plateau and supporting settlements', coordinates: [31.137, 29.976], radiusKm: 1.5, visibleFrom: -2500 },
    { name: 'Fustat', coordinates: [31.234, 30.006], radiusKm: 1, visibleFrom: 642 },
    { name: 'Fatimid nucleus', coordinates: [31.262, 30.049], radiusKm: 1, visibleFrom: 969 },
    { name: 'Citadel and Mamluk extensions', coordinates: [31.256, 30.032], radiusKm: 1.2, visibleFrom: 1363 },
    { name: 'Nineteenth-century central districts', coordinates: [31.243, 30.049], radiusKm: 1.4, visibleFrom: 1869 },
  ],
  sources: [
    { id: 'cairo-memphis-unesco', title: 'Memphis and its Necropolis: the Pyramid Fields from Giza to Dahshur', publisher: 'UNESCO World Heritage Centre', url: 'https://whc.unesco.org/en/list/86/' },
    { id: 'cairo-khufu-ministry', title: 'The Great Pyramid', publisher: 'Egyptian Ministry of Tourism and Antiquities', url: 'https://egymonuments.gov.eg/en/monuments/the-great-pyramid/' },
    { id: 'cairo-historic-unesco', title: 'Historic Cairo', publisher: 'UNESCO World Heritage Centre', url: 'https://whc.unesco.org/en/list/89/' },
    { id: 'cairo-amr-ministry', title: 'The Mosque of Amr ibn al-As', publisher: 'Egyptian Ministry of Tourism and Antiquities', url: 'https://egymonuments.gov.eg/monuments/the-mosque-of-amr-ibn-al-as' },
    { id: 'cairo-fatimids-ministry', title: 'Fatimid dynasty', publisher: 'Egyptian Ministry of Tourism and Antiquities', url: 'https://egymonuments.gov.eg/en/historical-periods/fatimids-dynasty' },
    { id: 'cairo-sultan-hassan-ministry', title: 'Mosque and Madrasa of Sultan Hasan', publisher: 'Egyptian Ministry of Tourism and Antiquities', url: 'https://egymonuments.gov.eg/en/monuments/mosque-and-madrasa-of-sultan-hasan' },
    { id: 'cairo-muhammad-ali-ministry', title: 'A virtual tour through the Muhammad Ali Mosque', publisher: 'Egyptian Ministry of Tourism and Antiquities', url: 'https://egymonuments.gov.eg/en/news/a-virtual-tour-through-the-muhammad-ali-mosque/' },
    { id: 'cairo-egyptian-museum-ministry', title: 'The Egyptian Museum: Our Story', publisher: 'Egyptian Ministry of Tourism and Antiquities', url: 'https://egymonuments.gov.eg/en/subportals-group/the-egyptian-museum/the-egyptian-museum-our-story' },
    { id: 'cairo-tower-tourism', title: 'Egypt Tourism Guide', publisher: 'Egyptian Tourism Authority / Experience Egypt', url: 'https://www.experienceegypt.eg/files/Egypt%20Tourism%20Guide-Eng.pdf' },
    { id: 'cairo-population-un', title: 'City population by sex, city and city type: Egypt, 2017, footnotes 1-2', publisher: 'United Nations Statistics Division, national census returns', url: 'https://data.un.org/Data.aspx?d=POP&f=tableCode%3A240%3BcountryCode%3A818' },
  ],
}
