import type { WorldCity } from '../types'

export const city: WorldCity = {
  id: 'london',
  name: 'London',
  country: 'United Kingdom',
  continent: 'Europe',
  tagline: 'A trading river, a rebuilt city, a connected metropolis.',
  center: [-0.115, 51.51],
  mapBounds: [-0.52, 51.35, 0.22, 51.68],
  historicalBounds: [-0.2, 51.45, 0.025, 51.56],
  reconstructionNote: 'Original generic symbolic miniatures, not architectural replicas or a surveyed reconstruction. District circles indicate approximate clusters, not boundaries. Viewing bounds include Heathrow and are not administrative borders. The hand-traced Thames is an orientation guide, not a verified historical riverbank. The 2025 endpoint means Modern: statistics retain their actual reference dates and sources may be updated beyond 2025.',
  chapters: [
    {
      year: 100,
      label: 'Roman Londinium',
      title: 'A port grows around the crossing',
      description: 'Londinium developed after the Roman conquest, around a bridge and trading quays on the Thames. Imported wine, pottery and glass connected this settlement to a much wider empire. Merchants, soldiers, craftspeople and enslaved people shared an unequal urban world. The amphitheatre and street grid mark a Roman town, not an ancient version of every neighbourhood in present-day London.',
      life: 'River cargoes supported workshops and markets. People arriving from different parts of the empire lived alongside local Britons; slavery and coercion were integral to this commercial prosperity, not incidental to it.',
      changes: ['Timber quays and a river crossing anchor an international trading town.', 'Public entertainment and a street grid give the settlement an urban centre.'],
      sources: ['london-roman-museum'],
      stats: [
        { label: 'Population benchmark', value: 'About 10,000', scope: 'Londinium; museum estimate, not Greater London or an AD 100 census', asOf: 'AD 60', source: 'london-roman-museum' },
        { label: 'Amphitheatre capacity', value: 'Up to 6,000 spectators', scope: 'Roman amphitheatre at present-day Guildhall Yard; approximate capacity', asOf: 'Roman period, established around AD 70', source: 'london-roman-museum' },
      ],
      focus: [-0.09, 51.513],
      spanKm: 3,
      density: 0.2,
    },
    {
      year: 1300,
      label: 'Medieval London',
      title: 'A merchant city between castle and court',
      description: 'The Norman fortress on the eastern edge of the City asserted royal power over an older commercial settlement. Farther upriver, Westminster developed as a centre of monarchy, worship and government. These were related but distinct urban cores. Between them, London grew through trade and institutions rather than a single comprehensive plan; medieval streets would remain influential long after their buildings disappeared.',
      life: 'Markets, workshops and religious institutions structured everyday routines. The river linked the merchant City to royal Westminster, while walls, gates and the castle made power and controlled access physically visible.',
      changes: ['The White Tower establishes a durable Norman stronghold beside the City.', 'Westminster and the merchant City develop complementary political and commercial roles.'],
      sources: ['london-tower-hrp', 'london-westminster-unesco'],
      stats: [
        { label: 'Population', value: 'Not reliably known', scope: 'London around 1300; these institutional sources do not establish a comparable citywide count', asOf: 'Around 1300', source: 'london-tower-hrp' },
        { label: 'White Tower height', value: 'About 90 ft / 27 m', scope: 'Central Norman keep, not the whole Tower of London complex', asOf: 'Medieval keep, completed around 1100', source: 'london-tower-hrp' },
      ],
      focus: [-0.091, 51.512],
      spanKm: 6,
      density: 0.35,
    },
    {
      year: 1666,
      label: 'Great Fire',
      title: 'Rebuilding without erasing the street map',
      description: 'Fire spread from Pudding Lane through the densely built City in September 1666. The disaster destroyed homes, workplaces and the old cathedral, but not all of London. Grand proposals for a new street plan collided with property rights and the urgency of rehousing people. Much of the medieval street network survived the rebuilding; Wren\'s new cathedral belongs to the decades that followed.',
      life: 'Displaced households needed shelter and income while owners and tenants negotiated rebuilding. The crisis was as much about housing and livelihoods as monumental architecture; surviving streets carried older patterns into the new city.',
      changes: ['The fire creates a housing emergency across the City of London.', 'Rebuilding largely retains existing streets rather than implementing a wholesale geometric plan.'],
      sources: ['london-fire-museum', 'london-stpauls'],
      stats: [
        { label: 'Houses destroyed', value: 'About 13,200', scope: 'Great Fire damage in the City of London, not all of modern London', asOf: 'September 1666', source: 'london-fire-museum' },
        { label: 'People made homeless', value: 'About 100,000', scope: 'Londoners displaced by the Great Fire; historical estimate', asOf: 'September 1666', source: 'london-fire-museum' },
      ],
      focus: [-0.086, 51.51],
      spanKm: 3,
      density: 0.25,
    },
    {
      year: 1894,
      label: 'Industrial and imperial',
      title: 'A bridge for a working port',
      description: 'Tower Bridge opened where a busy road crossing also had to admit tall ships. Its machinery expressed an industrial metropolis whose docks, railways and financial institutions reached across an empire. Those connections brought wealth unevenly, alongside exploitation overseas and hard conditions at home. The population benchmark uses a retrospectively comparable Greater London geography, not the much smaller nineteenth-century City of London.',
      life: 'Dock work, manufacturing, offices and expanding transport networks drew people across a much larger city. A lifting bridge balanced street traffic against river commerce, making daily movement part of a global trading system.',
      changes: ['Tower Bridge joins road traffic across the Thames without permanently blocking shipping.', 'Urban growth extends far beyond the medieval City and its population boundaries.'],
      sources: ['london-bridge', 'london-census-history'],
      stats: [
        { label: 'Population benchmark', value: '5,572,012', scope: 'Greater London area reconstructed in the historical census series; not the City corporation', asOf: '1891 census benchmark', source: 'london-census-history' },
        { label: 'Bridge steel framework', value: 'Over 11,000 tons', scope: 'Tower Bridge towers and walkways; source uses tons', asOf: 'Construction, 1886-1894', source: 'london-bridge' },
      ],
      focus: [-0.074, 51.506],
      spanKm: 8,
      density: 0.7,
    },
    {
      year: 1940,
      label: 'Twentieth-century war',
      title: 'The city under the Blitz',
      description: 'The Blitz began on 7 September 1940 with devastating attacks on London. Repeated bombing disrupted homes, industry and movement across the capital, although destruction was never uniform across the map. London was the most heavily and frequently bombed British city, but the campaign was national. These figures describe particular attacks and nights, not all British casualties or an invented wartime population.',
      life: 'Residents faced air-raid warnings, damaged homes and uncertain journeys while essential work continued. Shelter and recovery were collective tasks, experienced differently according to neighbourhood, occupation and access to safety and resources.',
      changes: ['Repeated air raids turn housing and civilian protection into urgent urban priorities.', 'Damaged districts enter a long process of repair and post-war redevelopment.'],
      sources: ['london-blitz-iwm'],
      stats: [
        { label: 'Consecutive bombing nights', value: '57', scope: 'London at the beginning of the Blitz', asOf: 'September-November 1940', source: 'london-blitz-iwm' },
        { label: 'People killed on Black Saturday', value: '430', scope: 'London attacks on the first day of the Blitz; not campaign-wide deaths', asOf: '7 September 1940', source: 'london-blitz-iwm' },
      ],
      focus: [-0.087, 51.515],
      spanKm: 8,
      density: 0.65,
    },
    {
      year: 2025,
      label: 'Modern - latest dated evidence',
      title: 'Historic centres in a cross-city network',
      description: 'Contemporary London combines old institutions with a transport network reaching far beyond its historic core. The Elizabeth line connects eastern and western corridors through central London, including Heathrow. This is the modern chapter, not a city frozen in 2025: the census remains explicitly dated 2021 and the linked operational sources can change. Metropolitan viewing bounds should never be mistaken for administrative borders.',
      life: 'Residents use overlapping rail, bus, walking and cycling networks to reach work, services and public spaces. Heritage remains part of ordinary urban life, alongside the continuing pressures of housing costs and unequal access.',
      changes: ['The Elizabeth line adds a high-capacity east-west connection through the centre.', 'A larger metropolitan perspective links historic districts to suburbs and the airport.'],
      sources: ['london-ons-2021', 'london-elizabeth-tfl'],
      stats: [
        { label: 'Usual resident population', value: '8,799,800', scope: 'London region / Greater London; rounded census figure, not the wider commuter region', asOf: '21 March 2021 census', source: 'london-ons-2021' },
        { label: 'Elizabeth line stations', value: '41', scope: 'Full Reading/Heathrow-Shenfield/Abbey Wood network, including stations outside London', asOf: 'TfL network information, accessed September 2026', source: 'london-elizabeth-tfl' },
      ],
      focus: [-0.117, 51.514],
      spanKm: 12,
      density: 0.95,
    },
  ],
  places: [
    { id: 'london-amphitheatre', name: 'Roman amphitheatre site', coordinates: [-0.0918, 51.5156], visibleFrom: 70, model: 'district', dateLabel: 'Established around AD 70; archaeological site', description: 'Public spectacles gathered thousands near the northern part of Roman Londinium, beneath today\'s Guildhall area.', caveat: 'Site marker only: neither the Roman arena nor the modern art gallery is reconstructed. Surviving archaeology is not an intact ancient building.', sources: ['london-roman-museum'] },
    { id: 'london-roman-port', name: 'Londinium riverfront', coordinates: [-0.087, 51.5088], visibleFrom: 50, model: 'district', dateLabel: 'Mid-first-century Roman trading riverfront', description: 'The north-bank quays connected London with goods and people across the Roman Empire, including the trade in enslaved people.', caveat: 'Approximate port-area anchor, not an excavated quay outline. The present river edge is not the Roman shoreline.', sources: ['london-roman-museum'] },
    { id: 'london-white-tower', name: 'White Tower', coordinates: [-0.0761, 51.5081], visibleFrom: 1100, model: 'fort', dateLabel: 'Begun in the 1070s; completed around 1100', description: 'The central Norman keep made royal military authority visible at the eastern edge of the City.', caveat: 'Generic keep symbol, not the real tower plan. Later outer walls and buildings are not projected into the medieval opening date.', sources: ['london-tower-hrp'] },
    { id: 'london-westminster', name: 'Westminster royal and religious precinct', coordinates: [-0.1277, 51.4994], visibleFrom: 1100, model: 'district', dateLabel: 'Royal and religious centre from the eleventh century', description: 'Palace and abbey formed a political and religious focus upstream from the commercial City.', caveat: 'Precinct marker only. The Gothic abbey and nineteenth-century Parliament buildings are successive later structures, not an eleventh-century skyline.', sources: ['london-westminster-unesco'] },
    { id: 'london-pudding-lane', name: 'Pudding Lane fire site', coordinates: [-0.0857, 51.5103], visibleFrom: 1666, model: 'district', dateLabel: 'Great Fire began here, September 1666', description: 'The fire\'s starting area anchors a story of destroyed housing and contested rebuilding rather than a preserved bakery.', caveat: 'Commemorative site anchor, not the bakery or the later Monument. No vanished building is shown as surviving.', sources: ['london-fire-museum'] },
    { id: 'london-stpauls', name: 'Wren\'s St Paul\'s Cathedral', coordinates: [-0.0984, 51.5138], visibleFrom: 1710, model: 'dome', dateLabel: 'Built 1675-1710 after the Great Fire', description: 'The domed cathedral is a product of the long rebuilding after 1666 and a lasting reference point in London\'s skyline.', caveat: 'Generic domed miniature, not an architectural replica. Deliberately absent from the 1666 chapter; the earlier cathedral was a different building.', sources: ['london-stpauls', 'london-fire-museum'] },
    { id: 'london-tower-bridge', name: 'Tower Bridge', coordinates: [-0.0754, 51.5055], visibleFrom: 1894, model: 'bridge', dateLabel: 'Opened 30 June 1894', description: 'An industrial steel bridge carries road traffic while lifting bascules preserve passage for shipping.', caveat: 'Symbolic bridge only; dimensions, machinery and tower detailing are not replicated.', sources: ['london-bridge'] },
    { id: 'london-elizabeth-line', name: 'Liverpool Street - Elizabeth line', coordinates: [-0.0828, 51.5186], visibleFrom: 2022, model: 'district', dateLabel: 'Central Elizabeth line opened May 2022', description: 'The City joins a rail corridor extending to Heathrow, Reading and eastern destinations.', caveat: 'Station-area marker for the new line, not a reconstruction of underground platforms or the older Liverpool Street terminus.', sources: ['london-elizabeth-tfl'] },
  ],
  water: [
    { name: 'Thames - schematic present-day course', kind: 'river', widthKm: 0.25, points: [[-0.27, 51.48], [-0.24, 51.47], [-0.205, 51.475], [-0.18, 51.477], [-0.16, 51.482], [-0.145, 51.489], [-0.126, 51.486], [-0.121, 51.499], [-0.118, 51.509], [-0.106, 51.511], [-0.087, 51.507], [-0.069, 51.505], [-0.049, 51.504], [-0.031, 51.49], [-0.014, 51.485], [0.005, 51.495]] },
  ],
  districts: [
    { name: 'Roman and medieval City', coordinates: [-0.091, 51.514], radiusKm: 0.9, visibleFrom: 100 },
    { name: 'Southwark river crossing', coordinates: [-0.089, 51.503], radiusKm: 0.65, visibleFrom: 100 },
    { name: 'Westminster precinct', coordinates: [-0.13, 51.5], radiusKm: 0.9, visibleFrom: 1300 },
    { name: 'West End growth', coordinates: [-0.143, 51.513], radiusKm: 1.1, visibleFrom: 1666 },
    { name: 'East End and docks', coordinates: [-0.053, 51.514], radiusKm: 1.4, visibleFrom: 1894 },
  ],
  sources: [
    { id: 'london-roman-museum', title: 'A timeline of Roman London: Londinium from start to end', publisher: 'London Museum', url: 'https://www.londonmuseum.org.uk/collections/london-stories/timeline-roman-london-londinium/' },
    { id: 'london-tower-hrp', title: 'History at the Tower', publisher: 'Historic Royal Palaces', url: 'https://www.hrp.org.uk/media/1171/tolhistory_v1.pdf' },
    { id: 'london-westminster-unesco', title: 'Palace of Westminster and Westminster Abbey including Saint Margaret\'s Church', publisher: 'UNESCO World Heritage Centre', url: 'https://whc.unesco.org/en/list/426/' },
    { id: 'london-fire-museum', title: 'How the Great Fire caused a London housing crisis', publisher: 'London Museum', url: 'https://www.londonmuseum.org.uk/collections/london-stories/great-fire-london-housing-crisis/' },
    { id: 'london-stpauls', title: 'Designs for the Dome, c. 1685-1710', publisher: 'St Paul\'s Cathedral', url: 'https://www.stpauls.co.uk/5-designs-for-dome-c-1685-1710' },
    { id: 'london-bridge', title: 'How was Tower Bridge built?', publisher: 'Tower Bridge / City of London Corporation', url: 'https://www.towerbridge.org.uk/stories/how-was-tower-bridge-built' },
    { id: 'london-blitz-iwm', title: 'The Blitz around Britain', publisher: 'Imperial War Museums', url: 'https://www.iwm.org.uk/history/second-world-war/blitz/blitz-around-britain' },
    { id: 'london-census-history', title: 'Historical Census Population', publisher: 'Greater London Authority / London Datastore', url: 'https://data.london.gov.uk/dataset/historical-census-population-expjm' },
    { id: 'london-ons-2021', title: 'London (E12000007): Census 2021 population', publisher: 'Office for National Statistics', url: 'https://www.ons.gov.uk/explore-local-statistics/areas/E12000007-london' },
    { id: 'london-elizabeth-tfl', title: 'Your journey by Elizabeth line', publisher: 'Transport for London', url: 'https://tfl.gov.uk/modes/elizabeth-line/your-journey-by-elizabeth-line' },
  ],
}
