import type { WorldCity } from '../types'

export const city: WorldCity = {
  id: 'new-york',
  name: 'New York',
  country: 'United States',
  continent: 'North America',
  tagline: 'Lenape homeland, an Atlantic port, a city of many arrivals.',
  center: [-73.99, 40.734],
  mapBounds: [-74.23, 40.49, -73.7, 40.94],
  historicalBounds: [-74.08, 40.665, -73.93, 40.825],
  reconstructionNote: 'Original generic symbolic miniatures, not architectural replicas. This is Lenape homeland before it is a colonial city; the first chapter date is a viewing anchor, not the beginning of Indigenous presence. District circles and density are illustrative. Viewing bounds include JFK and Newark airports, not municipal borders. Hand-traced Hudson, East River and harbour water are orientation only, not historical shorelines. Modern is an open-ended label with explicitly dated statistics, not a frozen 2025 count.',
  chapters: [
    {
      year: 1600,
      label: 'Lenape homeland',
      title: 'A populated landscape before New Amsterdam',
      description: 'Manhattan was part of the Lenape homeland long before a European colonial town existed. Paths, meeting places, waterways and seasonal resources connected communities across the region. The site later called Bowling Green is documented as a council ground and the end of an Indigenous trail. A 1600 chapter is only a chronological anchor: it does not assign a founding date to Lenape life.',
      life: 'Communities maintained relationships with land and water through food gathering, cultivation, travel and exchange. This explorer does not invent an individual voice or claim to recover a complete settlement map from later colonial records.',
      changes: ['The map begins with Indigenous places and connections, not an empty pre-colonial island.', 'Later Broadway and Bowling Green overlay an older route and meeting-ground history.'],
      sources: ['new-york-bowling-green', 'new-york-colonial-nps'],
      stats: [
        { label: 'Population', value: 'Not reliably known', scope: 'Lenape communities on Manhattan around 1600; no comparable enumeration is established by these sources', asOf: 'Around 1600', source: 'new-york-bowling-green' },
        { label: 'Documented civic landscape', value: 'Council ground and trail terminus', scope: 'Site later named Bowling Green; retrospective municipal historical account', asOf: 'Before European colonisation', source: 'new-york-bowling-green' },
      ],
      focus: [-74.012, 40.707],
      spanKm: 5,
      density: 0.1,
    },
    {
      year: 1664,
      label: 'Colonial port',
      title: 'New Amsterdam becomes New York',
      description: 'The Dutch colonial trading settlement at Manhattan\'s southern end grew around Atlantic commerce and the fur trade. Enslaved Africans performed essential work clearing roads and constructing fortifications and buildings. British seizure in 1664 renamed the colony New York; it did not begin the island\'s history. Colonial expansion displaced Indigenous communities and made unequal claims to land and labour central to the growing port.',
      life: 'Trading, waterfront work and construction sustained the settlement. Enslaved people helped create its infrastructure without equal rights, while colonial expansion constrained Indigenous landholding and movement; commercial growth cannot be separated from these coercive relationships.',
      changes: ['British rule replaces Dutch administration and introduces the name New York.', 'Enslaved labour builds streets, public structures and the cross-island stockade.'],
      sources: ['new-york-colonial-nps'],
      stats: [
        { label: 'Population', value: 'Not reliably known', scope: 'The 1664 colonial settlement; no single comparable count adopted from the cited account', asOf: '1664', source: 'new-york-colonial-nps' },
        { label: 'Fortified urban edge', value: 'Hudson-to-East River stockade', scope: 'Wall Street\'s predecessor under Dutch rule, constructed with enslaved labour', asOf: 'Dutch colonial period, before the 1664 takeover', source: 'new-york-colonial-nps' },
      ],
      focus: [-74.011, 40.706],
      spanKm: 3,
      density: 0.25,
    },
    {
      year: 1790,
      label: 'An early national capital',
      title: 'Federal government in a port city',
      description: 'New York briefly housed the new federal government. Washington took the presidential oath at the original Federal Hall in 1789, and the first Congress worked there before the capital moved to Philadelphia in 1790. The surviving Greek Revival building is a later Customs House. Census geography also matters: the 1790 city count must not be read as the population of today\'s five boroughs.',
      life: 'Government business shared streets with commerce and port work. A new constitutional order did not mean equal participation: political rights were restricted, and slavery remained legal in New York until the nineteenth century.',
      changes: ['Federal Hall houses the first constitutional Congress and presidential inauguration.', 'The federal capital moves to Philadelphia while New York\'s commercial role continues.'],
      sources: ['new-york-federal-hall', 'new-york-historical-census', 'new-york-colonial-nps'],
      stats: [
        { label: 'Census population', value: '33,131', scope: 'New York City as counted in 1790; not the subsequently consolidated five boroughs', asOf: '1790 census', source: 'new-york-historical-census' },
        { label: 'National legislature', value: 'First US Congress', scope: 'Original Federal Hall on Wall Street; institutional role, not the present building', asOf: '1789-1790', source: 'new-york-federal-hall' },
      ],
      focus: [-74.01, 40.709],
      spanKm: 3,
      density: 0.4,
    },
    {
      year: 1886,
      label: 'Bridges and arrival',
      title: 'A harbour gateway and an expanding city',
      description: 'The Brooklyn Bridge joined two still-separate cities in 1883. The Statue of Liberty was dedicated in 1886, becoming an enduring harbour symbol. Public landscaping also changed Manhattan, but Central Park\'s creation displaced residents, including the Black community of Seneca Village. These landmarks express ambition and access while exposing who paid for improvement; municipal consolidation into five boroughs still lay ahead.',
      life: 'Bridge crossings, harbour traffic and public recreation widened the city\'s daily horizons. New public spaces were not created on empty land, and industrial growth offered very different opportunities to owners, workers and newly arriving households.',
      changes: ['The Brooklyn Bridge creates a permanent crossing between New York and Brooklyn.', 'The Statue of Liberty becomes a new harbour landmark before five-borough consolidation.'],
      sources: ['new-york-bridge-dot', 'new-york-liberty-nps', 'new-york-central-park', 'new-york-historical-census'],
      stats: [
        { label: 'Population benchmark', value: '1,206,299', scope: 'New York City at its 1880 extent, before Brooklyn and the other boroughs were consolidated', asOf: '1880 census', source: 'new-york-historical-census' },
        { label: 'Liberty statue height', value: '151 ft 1 in', scope: 'Statue alone, excluding pedestal and foundation', asOf: 'Dedicated 28 October 1886', source: 'new-york-liberty-nps' },
      ],
      focus: [-74.001, 40.707],
      spanKm: 9,
      density: 0.7,
    },
    {
      year: 1931,
      label: 'The skyscraper city',
      title: 'Vertical ambition during the Depression',
      description: 'The Empire State Building opened in 1931 as a spectacular expression of engineering and commercial ambition during the Great Depression. Its skyline belongs to a consolidated five-borough city much larger than the earlier Manhattan-centred municipality. The 1930 census is a dated benchmark, not a precise count for opening day. Skyscrapers show one part of urban life rather than the condition of every neighbourhood.',
      life: 'Offices and dense transport networks organised work across a metropolitan economy, while the Depression brought unemployment and insecurity. The contrast between monumental construction and household hardship is essential to understanding this skyline.',
      changes: ['The Empire State Building adds a 102-storey landmark to Midtown.', 'The consolidated city\'s scale requires comparisons using five-borough rather than earlier municipal geography.'],
      sources: ['new-york-empire-state', 'new-york-historical-census'],
      stats: [
        { label: 'Population benchmark', value: '6,930,446', scope: 'New York City, all five boroughs; not the metropolitan region', asOf: '1930 census', source: 'new-york-historical-census' },
        { label: 'Empire State Building floors', value: '102', scope: 'The Empire State Building, Midtown Manhattan', asOf: 'Opened in 1931', source: 'new-york-empire-state' },
      ],
      focus: [-73.9857, 40.7484],
      spanKm: 8,
      density: 0.9,
    },
    {
      year: 2025,
      label: 'Modern - latest dated evidence',
      title: 'Five boroughs, memory and continued change',
      description: 'Contemporary New York combines global connections with neighbourhood histories extending well beyond Manhattan\'s landmarks. The 9/11 Memorial makes remembrance part of a redeveloped Lower Manhattan, while parks, bridges and older institutions remain in daily use. The modern endpoint is not a frozen 2025 population: the cited census describes 2020. Airport-inclusive viewing bounds show a metropolitan context, not the city\'s legal boundary.',
      life: 'Residents move between boroughs for work, family and services, navigating unequal housing and transport opportunities. Public places support everyday recreation and collective remembrance, while Indigenous and African American histories remain part of the living city.',
      changes: ['A memorial landscape occupies the former World Trade Center tower footprints.', 'Five-borough population evidence replaces misleading shorthand about Manhattan or the entire metro area.'],
      sources: ['new-york-census-2020', 'new-york-memorial'],
      stats: [
        { label: 'Census population', value: '8,804,190', scope: 'New York City, five boroughs; not Greater New York', asOf: '1 April 2020 census', source: 'new-york-census-2020' },
        { label: 'People commemorated', value: '2,977 + 6', scope: '2001 victims across all three attack locations, plus the six victims of the 1993 World Trade Center bombing', asOf: 'Attacks of 11 September 2001 and 26 February 1993', source: 'new-york-memorial' },
      ],
      focus: [-73.991, 40.737],
      spanKm: 12,
      density: 1,
    },
  ],
  places: [
    { id: 'new-york-lenape-council', name: 'Lenape council-ground site', coordinates: [-74.0134, 40.7047], visibleFrom: 1600, visibleUntil: 1733, model: 'district', dateLabel: 'Pre-colonial place; 1600 is a viewing anchor only', description: 'The site later called Bowling Green is recorded as a council ground and the terminus of an Indigenous trail.', caveat: 'Approximate retrospective site marker, not a reconstructed village. The later park is represented separately; the date does not imply Indigenous presence began or ended here in those years.', sources: ['new-york-bowling-green'] },
    { id: 'new-york-colonial-port', name: 'New Amsterdam port district', coordinates: [-74.0124, 40.7039], visibleFrom: 1626, model: 'district', dateLabel: 'Dutch settlement, 1620s; renamed in 1664', description: 'The southern tip of Manhattan anchors the colonial trading settlement and its dependence on enslaved labour.', caveat: 'District marker, not Fort Amsterdam or a reconstruction of its vanished walls. The modern shoreline includes later reclamation.', sources: ['new-york-colonial-nps'] },
    { id: 'new-york-bowling-green', name: 'Bowling Green', coordinates: [-74.0134, 40.7047], visibleFrom: 1733, model: 'park', dateLabel: 'Public park established 1733', description: 'The colonial public park overlays an older Indigenous meeting-place history.', caveat: 'Symbolic park only. Its present fence and landscaping are later layers, not all features of the 1733 opening.', sources: ['new-york-bowling-green'] },
    { id: 'new-york-old-federal-hall', name: 'Original Federal Hall site', coordinates: [-74.0103, 40.7074], visibleFrom: 1703, visibleUntil: 1812, model: 'district', dateLabel: 'City Hall completed 1703; Federal Hall 1789; demolished 1812', description: 'The earlier building hosted Washington\'s inauguration and the first constitutional Congress.', caveat: 'Site marker, not the surviving columned building. Removed from later scenes because this earlier structure was demolished in 1812.', sources: ['new-york-federal-hall'] },
    { id: 'new-york-federal-hall', name: 'Federal Hall - former Customs House', coordinates: [-74.0103, 40.7074], visibleFrom: 1842, model: 'temple', dateLabel: 'Present building opened 1842', description: 'The Greek Revival Customs House later became the Sub-Treasury and a memorial on an older governmental site.', caveat: 'Generic columned civic miniature, not a religious temple or architectural replica. Never shown as the building where Washington took his oath.', sources: ['new-york-federal-hall'] },
    { id: 'new-york-central-park', name: 'Central Park', coordinates: [-73.968, 40.7812], visibleFrom: 1858, model: 'park', dateLabel: 'Greensward Plan selected 1858; built in stages', description: 'A large designed public landscape offered recreation but displaced existing communities, including Seneca Village.', caveat: 'Generic green-space marker, not a natural pre-colonial landscape or a complete park at its first opening.', sources: ['new-york-central-park'] },
    { id: 'new-york-brooklyn-bridge', name: 'Brooklyn Bridge', coordinates: [-73.9969, 40.7061], visibleFrom: 1883, model: 'bridge', dateLabel: 'Opened 24 May 1883', description: 'The suspension bridge connected New York and Brooklyn before their political consolidation.', caveat: 'Generic symbolic bridge; no claim to reproduce its cable geometry, traffic lanes or engineering dimensions.', sources: ['new-york-bridge-dot'] },
    { id: 'new-york-liberty', name: 'Statue of Liberty', coordinates: [-74.0445, 40.6892], visibleFrom: 1886, model: 'statue', dateLabel: 'Dedicated 28 October 1886', description: 'The French gift became a harbour symbol of liberty with meanings shaped by later generations and migration.', caveat: 'Generic commemorative figure, not a sculptural replica. The modern museum is not included in the 1886 model.', sources: ['new-york-liberty-nps'] },
    { id: 'new-york-empire-state', name: 'Empire State Building', coordinates: [-73.9857, 40.7484], visibleFrom: 1931, model: 'tower', dateLabel: 'Opened 1931', description: 'A 102-storey skyscraper makes Midtown\'s early twentieth-century vertical growth tangible.', caveat: 'Original stepped-tower symbol, not an architectural replica. Never shown before 1931; later antenna changes are not separately modelled.', sources: ['new-york-empire-state'] },
    { id: 'new-york-911-memorial', name: '9/11 Memorial', coordinates: [-74.0132, 40.7115], visibleFrom: 2011, model: 'park', dateLabel: 'Memorial opened 2011', description: 'A public place of remembrance honours the victims of the 2001 attacks and the 1993 World Trade Center bombing.', caveat: 'Abstract memorial landscape, not a replica of the pools or a reconstruction of the attacks. The museum is a separate, later institution.', sources: ['new-york-memorial'] },
  ],
  water: [
    { name: 'Hudson River - schematic channel', kind: 'river', widthKm: 1.05, points: [[-73.96, 40.9], [-73.966, 40.879], [-73.972, 40.852], [-73.984, 40.828], [-73.997, 40.803], [-74.008, 40.781], [-74.019, 40.757], [-74.026, 40.735], [-74.028, 40.714], [-74.022, 40.694]] },
    { name: 'East River - schematic tidal strait', kind: 'river', widthKm: 0.5, points: [[-73.884, 40.803], [-73.911, 40.787], [-73.932, 40.777], [-73.951, 40.756], [-73.964, 40.741], [-73.97, 40.728], [-73.977, 40.712], [-73.99, 40.704], [-74.004, 40.701], [-74.016, 40.691]] },
    { name: 'Upper New York Bay - schematic water area', kind: 'area', points: [[-74.017, 40.702], [-74.003, 40.69], [-74.019, 40.671], [-74.032, 40.641], [-74.038, 40.613], [-74.054, 40.606], [-74.072, 40.633], [-74.088, 40.652], [-74.077, 40.671], [-74.061, 40.687], [-74.041, 40.708], [-74.017, 40.702]] },
  ],
  districts: [
    { name: 'Southern Manhattan Indigenous landscape', coordinates: [-74.007, 40.709], radiusKm: 1.2, visibleFrom: 1600 },
    { name: 'Colonial port and Wall Street', coordinates: [-74.01, 40.707], radiusKm: 0.75, visibleFrom: 1664 },
    { name: 'Brooklyn waterfront', coordinates: [-73.994, 40.699], radiusKm: 1.1, visibleFrom: 1886 },
    { name: 'Midtown', coordinates: [-73.985, 40.753], radiusKm: 1.6, visibleFrom: 1931 },
    { name: 'Uptown neighbourhoods', coordinates: [-73.955, 40.808], radiusKm: 1.1, visibleFrom: 1931 },
  ],
  sources: [
    { id: 'new-york-bowling-green', title: 'New York City\'s oldest park gets a makeover: Bowling Green history', publisher: 'New York City Department of Parks & Recreation', url: 'https://www.nycgovparks.org/parks/bowling-green/dailyplant/19049' },
    { id: 'new-york-colonial-nps', title: 'Colonial African Enslavement', publisher: 'National Park Service, African Burial Ground National Monument', url: 'https://www.nps.gov/afbg/learn/historyculture/enslavement.htm' },
    { id: 'new-york-historical-census', title: 'Population of the 100 Largest Cities and Other Urban Places in the United States: 1790 to 1990', publisher: 'US Census Bureau', url: 'https://www.census.gov/library/working-papers/1998/demo/POP-twps0027.html' },
    { id: 'new-york-federal-hall', title: 'Federal Hall: History & Culture', publisher: 'National Park Service', url: 'https://www.nps.gov/feha/learn/hc.htm' },
    { id: 'new-york-bridge-dot', title: 'Brooklyn Bridge', publisher: 'New York City Department of Transportation', url: 'https://www.nyc.gov/html/dot/html/infrastructure/brooklyn-bridge.shtml' },
    { id: 'new-york-liberty-nps', title: 'Fact Sheet: Statue of Liberty National Monument', publisher: 'National Park Service', url: 'https://www.nps.gov/npnh/learn/news/fact-sheet-stli.htm' },
    { id: 'new-york-central-park', title: 'Our Story Timeline', publisher: 'Central Park Conservancy', url: 'https://www.centralparknyc.org/our-story-timeline' },
    { id: 'new-york-empire-state', title: 'Empire State Building Facts & Figures', publisher: 'Empire State Realty Trust', url: 'https://www.esbnyc.com/about/facts-figures' },
    { id: 'new-york-census-2020', title: 'NYC Population FactFinder: city population', publisher: 'New York City Department of City Planning / US Census Bureau', url: 'https://popfactfinder.planning.nyc.gov/explorer/districts/110' },
    { id: 'new-york-memorial', title: 'About the Memorial', publisher: 'National September 11 Memorial & Museum', url: 'https://www.911memorial.org/visit/memorial/about-memorial' },
  ],
}
