import type { WorldCity } from '../types'

export const city: WorldCity = {
  id: 'rio',
  name: 'Rio de Janeiro',
  country: 'Brazil',
  continent: 'South America',
  tagline: 'Indigenous Guanabara, an imperial port, and a mountain-sea city.',
  center: [-43.204, -22.928],
  mapBounds: [-43.48, -23.08, -43.02, -22.72],
  historicalBounds: [-43.3, -23.0, -43.14, -22.86],
  reconstructionNote: 'Original generic symbolic miniatures, not architectural replicas. Indigenous history predates the 1500 viewing anchor; the Portuguese city was founded in 1565. District seeds and density are illustrative, not exact settlements or territorial claims. Airport-inclusive viewing bounds contain Galeao and Santos Dumont, not municipal borders. Hand-traced bay and Atlantic polygons are orientation only: reclamation and historical shorelines are not reconstructed. Modern is an open-ended 2025 label with individually dated evidence.',
  chapters: [
    {
      year: 1500,
      label: 'Indigenous Guanabara',
      title: 'A lived bay before the colonial city',
      description: 'Guanabara was a lived Indigenous region before Portuguese city-building. Tupinamba and Temimino histories are part of that landscape, not a preface to an otherwise empty map. Villages, cultivation, fishing and travel connected land and water. The first chapter uses 1500 as an orientation date; it neither dates the beginning of Indigenous presence nor claims to reconstruct the precise location of every community.',
      life: 'Fishing, cultivation, exchange and relationships between communities supported life around the bay. Sources preserve only partial accounts, often mediated by outsiders; no invented personal voice or exact settlement population is supplied here.',
      changes: ['The opening view recognises Indigenous occupation and connections across Guanabara.', 'Mountain and water anchors are separated from the much later colonial buildings and tourist infrastructure.'],
      sources: ['rio-indigenous-museum', 'rio-tupinamba-ibge', 'rio-landscape-unesco'],
      stats: [
        { label: 'Population', value: 'Not reliably known', scope: 'Indigenous communities around Guanabara; no defensible region-wide count is adopted', asOf: 'Around 1500', source: 'rio-indigenous-museum' },
        { label: 'Documented settlement form', value: 'Communal houses in villages', scope: 'Tupinamba ways of life described by IBGE; not a surveyed layout for a specific Guanabara village', asOf: 'Sixteenth-century accounts, interpreted retrospectively', source: 'rio-tupinamba-ibge' },
      ],
      focus: [-43.168, -22.934],
      spanKm: 8,
      density: 0.1,
    },
    {
      year: 1565,
      label: 'Portuguese colonial foothold',
      title: 'A fortified foundation in a contested bay',
      description: 'Estacio de Sa founded Sao Sebastiao do Rio de Janeiro in 1565 near Morro Cara de Cao. The settlement was part of a struggle involving Portuguese and French colonisers and Indigenous peoples with their own interests and alliances. Portuguese victory was not an uncomplicated founding celebration: warfare, dispossession and imposed colonial authority transformed an already inhabited region and its relationships to land and water.',
      life: 'Fortification, provisioning and movement by water supported the precarious colonial settlement. Indigenous communities faced warfare and displacement, while alliances differed; treating all local peoples as one side would erase their distinct political choices.',
      changes: ['A Portuguese fortified settlement claims a foothold near the entrance to Guanabara Bay.', 'Colonial warfare and expansion disrupt Indigenous occupation and control of the region.'],
      sources: ['rio-foundation-city', 'rio-indigenous-museum'],
      stats: [
        { label: 'Population', value: 'Not reliably known', scope: 'The 1565 Portuguese settlement, separately from the bay\'s Indigenous population', asOf: '1565', source: 'rio-foundation-city' },
        { label: 'Founding settlement', value: 'Fortified foothold at Cara de Cao', scope: 'Original Sao Sebastiao site near Urca, not the later central business district', asOf: '1 March 1565', source: 'rio-foundation-city' },
      ],
      focus: [-43.158, -22.943],
      spanKm: 4,
      density: 0.15,
    },
    {
      year: 1763,
      label: 'Colonial capital',
      title: 'Government gathers beside the port',
      description: 'Rio became the capital of colonial Brazil in 1763, shifting the centre of government from Salvador toward this Atlantic port. The governor\'s palace, later known as the Paco Imperial, became associated with vice-regal power. Administrative importance and maritime commerce reinforced one another. The city\'s growth was inseparable from an economy built on slavery, although the surviving Valongo Wharf belongs to the following century.',
      life: 'Government business, port labour and trade concentrated activity around the waterfront and civic centre. Wealth circulated through a deeply unequal society, where enslaved workers sustained households and commerce without enjoying the freedoms their work supported.',
      changes: ['Rio takes over the colonial capital role from Salvador.', 'The palace and adjacent waterfront consolidate an administrative and commercial centre.'],
      sources: ['rio-foundation-city', 'rio-paco-iphan', 'rio-valongo-unesco'],
      stats: [
        { label: 'Population', value: 'Not reliably known', scope: 'Rio at the 1763 snapshot; these sources do not establish a comparable citywide total', asOf: '1763', source: 'rio-paco-iphan' },
        { label: 'Government role', value: 'Vice-regal capital of Brazil', scope: 'Rio de Janeiro as colonial administrative seat, succeeding Salvador', asOf: '1763', source: 'rio-paco-iphan' },
      ],
      focus: [-43.175, -22.904],
      spanKm: 4,
      density: 0.35,
    },
    {
      year: 1822,
      label: 'Royal court to empire',
      title: 'Independence without emancipation',
      description: 'The Portuguese court\'s arrival in 1808 changed Rio\'s institutions and political scale. A botanical garden was established that year, and the palace acquired a royal role. Independence in 1822 made Rio an imperial capital, but did not abolish slavery. Valongo Wharf, built from 1811, makes the city\'s role in the forced movement of Africans impossible to separate from its monumental and institutional growth.',
      life: 'Court administration and new institutions created work and demanded resources, while enslaved people carried much of the burden. Political independence changed the state without granting universal freedom; African contributions remain central to the city\'s history.',
      changes: ['Royal institutions established after 1808 become part of the independent empire\'s capital.', 'Valongo formalises a major landing place in the Atlantic trafficking of enslaved Africans.'],
      sources: ['rio-paco-iphan', 'rio-paco-history', 'rio-landscape-unesco', 'rio-valongo-unesco'],
      stats: [
        { label: 'Population', value: 'Not reliably known', scope: 'Rio at independence; no comparable total adopted from these institutional sources', asOf: '1822', source: 'rio-paco-history' },
        { label: 'Scientific institution', value: 'Royal botanical garden', scope: 'Rio\'s Botanical Garden, a surviving institution south of the old administrative centre', asOf: 'Established in 1808', source: 'rio-landscape-unesco' },
      ],
      focus: [-43.183, -22.901],
      spanKm: 6,
      density: 0.5,
    },
    {
      year: 1931,
      label: 'A twentieth-century skyline',
      title: 'A new monument on an older mountain',
      description: 'Christ the Redeemer was inaugurated on Corcovado in October 1931 after a construction campaign beginning in 1926. The statue became an internationally recognised image, but the mountain and surrounding city had much older histories. Rio\'s dramatic landscape was also actively reshaped through transport, planting and waterfront design. The miniature introduces the statue only now, rather than placing a modern landmark in colonial scenes.',
      life: 'The monument linked engineering, religious patronage and public fundraising. Beyond the celebrated skyline, people lived in neighbourhoods with sharply different access to services and opportunity; a famous image should not stand in for the whole city.',
      changes: ['Christ the Redeemer adds a monumental twentieth-century layer to Corcovado.', 'The mountain-sea landscape becomes increasingly central to Rio\'s international identity.'],
      sources: ['rio-redeemer-assembly', 'rio-landscape-unesco'],
      stats: [
        { label: 'Monument height', value: '38 m including base', scope: 'Christ the Redeemer: 30 m statue plus 8 m pedestal, not the mountain elevation', asOf: 'Inaugurated 12 October 1931', source: 'rio-redeemer-assembly' },
        { label: 'Construction campaign', value: '5 years', scope: 'Christ the Redeemer, from the 1926 start to the 1931 inauguration', asOf: '1926-1931', source: 'rio-redeemer-assembly' },
      ],
      focus: [-43.207, -22.943],
      spanKm: 10,
      density: 0.75,
    },
    {
      year: 2025,
      label: 'Modern - latest dated evidence',
      title: 'A living landscape and a site of conscience',
      description: 'Modern Rio is both a densely inhabited municipality and a landscape shaped by mountains, water and deliberate urban design. Valongo\'s exposed archaeology adds an essential history of enslavement and African heritage to familiar postcard views. The modern endpoint is not a frozen 2025 census. Population and density refer explicitly to the 2022 municipality, not Rio state or the larger metropolitan region.',
      life: 'Neighbourhoods connect through work, recreation and public space, while unequal access remains important. Conservation involves living communities as well as scenery; Valongo supports remembrance and African-Brazilian cultural practices rather than functioning only as an archaeological exhibit.',
      changes: ['Landscape conservation and urban pressures must be considered together, not as separate stories.', 'Valongo\'s recovered remains make slavery and African heritage visible within the contemporary port district.'],
      sources: ['rio-census-ibge', 'rio-landscape-unesco', 'rio-valongo-unesco'],
      stats: [
        { label: 'Census population', value: '6,211,423', scope: 'Rio de Janeiro municipality; not the state or metropolitan area', asOf: '2022 census', source: 'rio-census-ibge' },
        { label: 'Population density', value: '5,174.60 people/km2', scope: 'Rio de Janeiro municipality; administrative-area average, not built-up neighbourhood density', asOf: '2022 census', source: 'rio-census-ibge' },
        { label: 'Forced arrivals at Valongo', value: 'Up to 900,000, estimated', scope: 'African captives over the wharf\'s slave-trade history; UNESCO estimate, not a present population', asOf: 'Nineteenth-century operation beginning in 1811; retrospective estimate', source: 'rio-valongo-unesco' },
      ],
      focus: [-43.199, -22.917],
      spanKm: 12,
      density: 0.95,
    },
  ],
  places: [
    { id: 'rio-guanabara', name: 'Guanabara Indigenous landscape', coordinates: [-43.176, -22.935], visibleFrom: 1500, model: 'district', dateLabel: 'Indigenous presence predates the 1500 viewing anchor', description: 'The bay linked Indigenous communities through travel, livelihoods and political relationships before Portuguese city-building.', caveat: 'Regional interpretive anchor near Botafogo, not the excavated coordinates of a named village or a claim of an exact territorial boundary.', sources: ['rio-indigenous-museum', 'rio-tupinamba-ibge'] },
    { id: 'rio-sugarloaf', name: 'Sugarloaf / Pao de Acucar', coordinates: [-43.1566, -22.9486], visibleFrom: 1500, model: 'hill', dateLabel: 'Natural landform; no human founding date', description: 'The mountain helps define the entrance to Guanabara and the city\'s relationship with its dramatic topography.', caveat: 'Symbolic hill only, with no modern cableway projected into early chapters. The date controls the explorer, not the age of the mountain.', sources: ['rio-landscape-unesco'] },
    { id: 'rio-cara-de-cao', name: 'Morro Cara de Cao founding area', coordinates: [-43.158, -22.943], visibleFrom: 1565, model: 'district', dateLabel: 'Portuguese settlement founded 1 March 1565', description: 'The original colonial foothold lay near Urca rather than at the later civic centre.', caveat: 'Approximate founding-area marker, not a replica of the original fort or the present military complex.', sources: ['rio-foundation-city'] },
    { id: 'rio-paco-imperial', name: 'Paco Imperial', coordinates: [-43.1743, -22.9037], visibleFrom: 1743, model: 'palace', dateLabel: 'Governor\'s palace completed 1743; later royal and imperial uses', description: 'The waterfront palace accumulated colonial, royal and imperial governmental roles before becoming a cultural centre.', caveat: 'Generic palace symbol, not a replica. Its name and function changed; it was not already an imperial palace in 1743.', sources: ['rio-paco-iphan', 'rio-paco-history'] },
    { id: 'rio-botanical-garden', name: 'Rio Botanical Garden', coordinates: [-43.2245, -22.9673], visibleFrom: 1808, model: 'park', dateLabel: 'Established 1808', description: 'A royal-era scientific and planted landscape became part of Rio\'s protected mountain-to-sea cultural setting.', caveat: 'Generic garden marker. Present plantings and paths accumulated later and are not a reconstruction of the original collection.', sources: ['rio-landscape-unesco'] },
    { id: 'rio-valongo', name: 'Valongo Wharf archaeological site', coordinates: [-43.1872, -22.8967], visibleFrom: 1811, model: 'district', dateLabel: 'Wharf from 1811; overlaid in 1843; excavated 2011', description: 'The surviving landing-place remains confront the scale and human cost of the Atlantic slave trade.', caveat: 'Site marker across its history, not a continuously exposed or intact wharf. Later layers and reclamation separated the remains from today\'s water edge.', sources: ['rio-valongo-unesco'] },
    { id: 'rio-redeemer', name: 'Christ the Redeemer', coordinates: [-43.2105, -22.9519], visibleFrom: 1931, model: 'statue', dateLabel: 'Inaugurated 12 October 1931', description: 'The 30-metre statue and 8-metre pedestal add a modern religious monument to Corcovado.', caveat: 'Original generic commemorative figure, not a sculptural replica. Never shown before 1931; the mountain existed long before the monument.', sources: ['rio-redeemer-assembly'] },
    { id: 'rio-tijuca', name: 'Tijuca National Park - eastern forest', coordinates: [-43.246, -22.946], visibleFrom: 1961, model: 'park', dateLabel: 'National park created 1961; forest restoration began earlier', description: 'Protected forested mountains are part of a cultural landscape shaped by restoration as well as natural processes.', caveat: 'Approximate eastern-forest anchor, not the entire national park boundary. It does not claim this restored forest is untouched pre-colonial vegetation.', sources: ['rio-landscape-unesco'] },
  ],
  water: [
    { name: 'Guanabara Bay - schematic water area', kind: 'area', points: [[-43.148, -22.94], [-43.172, -22.915], [-43.17, -22.894], [-43.207, -22.875], [-43.22, -22.84], [-43.232, -22.796], [-43.197, -22.755], [-43.12, -22.742], [-43.057, -22.782], [-43.064, -22.826], [-43.088, -22.867], [-43.122, -22.904], [-43.121, -22.935], [-43.148, -22.94]] },
    { name: 'Atlantic edge - schematic coastal water', kind: 'area', points: [[-43.121, -22.935], [-43.145, -22.956], [-43.169, -22.965], [-43.18, -22.979], [-43.197, -22.988], [-43.212, -22.988], [-43.227, -22.987], [-43.246, -22.991], [-43.275, -23.016], [-43.33, -23.025], [-43.34, -23.08], [-43.08, -23.08], [-43.08, -22.96], [-43.121, -22.935]] },
  ],
  districts: [
    { name: 'Guanabara communities - regional seed', coordinates: [-43.174, -22.935], radiusKm: 1.2, visibleFrom: 1500 },
    { name: 'Urca colonial foothold', coordinates: [-43.16, -22.942], radiusKm: 0.65, visibleFrom: 1565 },
    { name: 'Praca XV civic core', coordinates: [-43.175, -22.904], radiusKm: 0.9, visibleFrom: 1763 },
    { name: 'Valongo and port district', coordinates: [-43.188, -22.898], radiusKm: 0.9, visibleFrom: 1822 },
    { name: 'Southern neighbourhoods', coordinates: [-43.187, -22.965], radiusKm: 1.5, visibleFrom: 1931 },
  ],
  sources: [
    { id: 'rio-indigenous-museum', title: 'A presenca indigena no Rio de Janeiro', publisher: 'Museu do Indio / FUNAI', url: 'https://antigo.museudoindio.gov.br/divulgacao/noticias/910-a-presenca-indigena-no-rio-de-janeiro' },
    { id: 'rio-tupinamba-ibge', title: 'Modos de vida dos Tupinamba ou Tupis', publisher: 'IBGE, Brasil: 500 anos de povoamento', url: 'https://brasil500anos.ibge.gov.br/en/territorio-brasileiro-e-povoamento/historia-indigena/modos-de-vida-dos-tupinamba-ou-tupis' },
    { id: 'rio-foundation-city', title: 'Rio de Janeiro: the city\'s founding', publisher: 'Prefeitura da Cidade do Rio de Janeiro', url: 'https://www.rio.rj.gov.br/web/guest/exibeconteudo?id=7717030' },
    { id: 'rio-paco-iphan', title: 'Centro Cultural do Patrimonio Paco Imperial: historical booklet', publisher: 'Instituto do Patrimonio Historico e Artistico Nacional', url: 'https://www.gov.br/iphan/pt-br/unidades-especiais/centro-cultural-paco-imperial/PACO_20200202_LivretoHistoria_AF_spreadBaixa.pdf/@@download/file/PACO_20200202_LivretoHistoria_AF_spreadBaixa.pdf' },
    { id: 'rio-paco-history', title: 'Historico e Missao', publisher: 'Associacao dos Amigos do Paco Imperial', url: 'https://amigosdopacoimperial.org.br/missao/' },
    { id: 'rio-landscape-unesco', title: 'Rio de Janeiro: Carioca Landscapes between the Mountain and the Sea', publisher: 'UNESCO World Heritage Centre', url: 'https://whc.unesco.org/en/list/1100/' },
    { id: 'rio-valongo-unesco', title: 'Valongo Wharf Archaeological Site', publisher: 'UNESCO World Heritage Centre', url: 'https://whc.unesco.org/en/list/1548/' },
    { id: 'rio-redeemer-assembly', title: 'Cristo Redentor: cartao postal do Brasil', publisher: 'Assembleia Legislativa do Estado de Sao Paulo', url: 'https://www.al.sp.gov.br/noticia/?id=262263' },
    { id: 'rio-census-ibge', title: 'Rio de Janeiro municipality: population and density', publisher: 'Instituto Brasileiro de Geografia e Estatistica', url: 'https://cidades.ibge.gov.br/brasil/rj/rio-de-janeiro/panorama' },
  ],
}
