import type { WorldCity } from '../types'

export const city: WorldCity = {
  id: 'sydney',
  name: 'Sydney',
  country: 'Australia',
  continent: 'Oceania',
  tagline: 'Gadigal Country, a colonial harbour, and a connected coastal city.',
  center: [151.209, -33.865],
  mapBounds: [150.85, -34.05, 151.35, -33.66],
  historicalBounds: [151.12, -33.93, 151.3, -33.81],
  reconstructionNote: 'Original generic symbolic miniatures, not architectural replicas. The 1600 anchor is not the beginning of Aboriginal presence or a reconstructed village map; connection to Country continues today. District circles and density are approximate. Viewing bounds include Sydney Airport, not municipal or Greater Sydney borders. Hand-traced harbour geometry is orientation only, not a verified historical shoreline. Modern is an open-ended 2025 label; census and institutional facts retain their actual dates.',
  chapters: [
    {
      year: 1600,
      label: 'Aboriginal Country',
      title: 'A harbour of relationships before the colony',
      description: 'The harbour and central Sydney are Gadigal Country within a wider region of distinct Aboriginal communities. Waterways, food resources, places and relationships structured life long before British arrival. The explorer\'s 1600 anchor does not date the beginning of that history. It also does not claim an exact pre-colonial settlement map: surviving records are partial, while Aboriginal custodianship and cultural life continue into the present.',
      life: 'Fishing, movement by water and knowledge of Country supported community life. These histories are not represented through invented first-person speech, and contemporary Aboriginal people are not treated as belonging only to a vanished past.',
      changes: ['The opening view recognises inhabited Country rather than an empty future colony.', 'Harbour places are shown without later bridges, colonial buildings or the Opera House.'],
      sources: ['sydney-gadi-museum'],
      stats: [
        { label: 'Population', value: 'Not reliably known', scope: 'Gadigal communities around central Sydney at this viewing date; no comparable enumeration is available here', asOf: 'Around 1600', source: 'sydney-gadi-museum' },
        { label: 'Custodianship', value: 'Gadigal Country', scope: 'Central Sydney; part of a wider Aboriginal region, not a single homogeneous population', asOf: 'Before 1788 and continuing today', source: 'sydney-gadi-museum' },
      ],
      focus: [151.215, -33.855],
      spanKm: 6,
      density: 0.1,
    },
    {
      year: 1788,
      label: 'British colonisation',
      title: 'A penal settlement at Warrane',
      description: 'The First Fleet reached Botany Bay and then established the British settlement at Sydney Cove, Warrane, on 26 January 1788. Colonial accounts describe ships and personnel, but their totals are not the population of the whole harbour region. Colonisation brought dispossession, violence and devastating disease to Aboriginal communities. The Rocks developed on the western side of the cove, within Country that was already inhabited.',
      life: 'Convicts, marines and officials faced provisioning problems and a harsh penal regime. Aboriginal people confronted an expanding occupation of their land; their continued presence and resistance cannot be reduced to the fleet\'s arrival narrative.',
      changes: ['A British penal settlement occupies Warrane and the western side of Sydney Cove.', 'Colonial expansion disrupts Aboriginal access to land, resources and security.'],
      sources: ['sydney-first-fleet-library', 'sydney-rocks-history'],
      stats: [
        { label: 'First Fleet vessels', value: '11 ships', scope: 'Fleet travelling from Britain to the new colony', asOf: 'Voyage of 1787-1788', source: 'sydney-first-fleet-library' },
        { label: 'People aboard at departure', value: 'About 1,500', scope: 'Fleet complement including crew, marines, families and convicts; not Sydney\'s total population on arrival', asOf: 'Departure from England, May 1787', source: 'sydney-first-fleet-library' },
      ],
      focus: [151.21, -33.858],
      spanKm: 3,
      density: 0.2,
    },
    {
      year: 1855,
      label: 'Colonial growth and rail',
      title: 'Beyond the cove by steam',
      description: 'The first railway in New South Wales opened in September 1855, linking Sydney with Parramatta Junction at present-day Granville. Its terminal lay near, but not at, today\'s Central Station. The colony\'s older institutions were changing too: Hyde Park Barracks had moved from convict accommodation to an immigration depot. Railways widened the city\'s connections without making colonial land ownership or social opportunity equal.',
      life: 'New rail services supplemented journeys by road and water. Government institutions organised the lives of convicts and later immigrants, while the expanding settlement continued to transform Aboriginal Country and neighbourhood patterns far beyond the first cove.',
      changes: ['The 22-kilometre railway introduces a new connection to the western settlements.', 'Former convict accommodation takes on new immigration and institutional functions.'],
      sources: ['sydney-rail-mhnsw', 'sydney-barracks-mhnsw'],
      stats: [
        { label: 'First NSW railway length', value: '22 km', scope: 'Original Sydney terminus to Parramatta Junction, now Granville; not today\'s entire line', asOf: 'Opened 26 September 1855', source: 'sydney-rail-mhnsw' },
        { label: 'Original barracks capacity', value: '600 men', scope: 'Hyde Park Barracks planned convict accommodation; not its later immigrant occupancy', asOf: 'Opening design, 1819', source: 'sydney-barracks-mhnsw' },
      ],
      focus: [151.205, -33.878],
      spanKm: 6,
      density: 0.45,
    },
    {
      year: 1932,
      label: 'The harbour crossing',
      title: 'A steel arch changes daily movement',
      description: 'Sydney Harbour Bridge opened in March 1932, joining the central city and North Shore through a monumental transport project. The bridge made road and rail connections visible in one continuous arch, while ferries remained part of harbour life. Construction was a major engineering and labour undertaking. This is a twentieth-century structure, not an enduring feature of the earlier Aboriginal or colonial harbour scenes.',
      life: 'The crossing changed journeys between home and work on opposite sides of the harbour. Its opening during the Depression also placed civic ambition beside household insecurity; transport infrastructure did not remove the city\'s social inequalities.',
      changes: ['Road and rail acquire a permanent central harbour crossing.', 'The bridge ties the North Shore more directly into the city\'s daily transport network.'],
      sources: ['sydney-bridge-transport'],
      stats: [
        { label: 'Main arch span', value: '503 m', scope: 'Sydney Harbour Bridge main arch; not its total length including approaches', asOf: 'Opened 19 March 1932', source: 'sydney-bridge-transport' },
        { label: 'Steel used', value: '52,800 tonnes', scope: 'Sydney Harbour Bridge construction', asOf: 'Completed project, 1932', source: 'sydney-bridge-transport' },
      ],
      focus: [151.21, -33.856],
      spanKm: 6,
      density: 0.7,
    },
    {
      year: 1973,
      label: 'The Opera House opens',
      title: 'A performance building on a layered headland',
      description: 'The Sydney Opera House opened in October 1973 after fourteen years of construction. Jorn Utzon\'s ambitious design required major engineering work and a large construction workforce. The site had previously held the Fort Macquarie tram depot and has a much longer Aboriginal history. The finished building belongs only to this later chapter, not to the place\'s earlier cultural or colonial layers.',
      life: 'The new performing-arts institution expanded public cultural life and changed the harbour\'s image. Its creation depended on many workers as well as a celebrated designer, and the completed landmark did not erase the histories of its site.',
      changes: ['A major performing-arts institution replaces the headland\'s earlier transport use.', 'Fourteen years of construction produce a new internationally recognisable harbour landmark.'],
      sources: ['sydney-opera-nfsa', 'sydney-gadi-museum'],
      stats: [
        { label: 'Construction duration', value: '14 years', scope: 'Sydney Opera House building project', asOf: '1959 to opening on 20 October 1973', source: 'sydney-opera-nfsa' },
        { label: 'Construction workforce', value: 'About 10,000 workers', scope: 'People involved over the Opera House construction project; not simultaneous onsite employment', asOf: '1959-1973', source: 'sydney-opera-nfsa' },
      ],
      focus: [151.215, -33.858],
      spanKm: 6,
      density: 0.8,
    },
    {
      year: 2025,
      label: 'Modern - latest dated evidence',
      title: 'A metropolitan city reworks its waterfront',
      description: 'Modern Sydney extends well beyond the harbour landmarks and the small City of Sydney municipality. Barangaroo Reserve shows how a former industrial waterfront can become designed public space, not a recovered untouched shoreline. This endpoint means modern rather than a city frozen in 2025. The population is explicitly the 2021 Greater Sydney census profile; it is not a current estimate or a municipal count.',
      life: 'Residents connect homes, jobs and services across a large metropolitan region. Waterfront parks and cultural institutions offer shared spaces, while housing, travel time and continued recognition of Aboriginal Country shape access to the city.',
      changes: ['Barangaroo Reserve returns a redesigned former industrial waterfront to public use.', 'Metropolitan census geography separates Greater Sydney from the much smaller central municipality.'],
      sources: ['sydney-abs-2021', 'sydney-barangaroo', 'sydney-gadi-museum'],
      stats: [
        { label: 'Census profile population', value: '5,231,147', scope: 'Greater Sydney GCCSA (1GSYD), not City of Sydney LGA; ABS QuickStats applies small privacy adjustments', asOf: '10 August 2021 census', source: 'sydney-abs-2021' },
        { label: 'Reserve sandstone blocks', value: 'About 10,000', scope: 'Barangaroo Reserve landscape construction; not an ancient shoreline count', asOf: 'Reserve opened in 2015; project account', source: 'sydney-barangaroo' },
      ],
      focus: [151.205, -33.866],
      spanKm: 12,
      density: 0.95,
    },
  ],
  places: [
    { id: 'sydney-warrane', name: 'Warrane / Sydney Cove', coordinates: [151.212, -33.858], visibleFrom: 1600, model: 'district', dateLabel: 'Aboriginal place before 1788; 1600 is a viewing anchor', description: 'The cove is part of a lived Aboriginal harbour landscape and later became the focus of the British penal settlement.', caveat: 'Place marker, not a reconstructed village, exact pre-colonial shoreline or founding date for Gadigal presence.', sources: ['sydney-gadi-museum', 'sydney-first-fleet-library'] },
    { id: 'sydney-rocks', name: 'The Rocks colonial district', coordinates: [151.208, -33.859], visibleFrom: 1788, model: 'district', dateLabel: 'Colonial settlement from 1788 on earlier Aboriginal Country', description: 'The western cove became a colonial town centre through an occupation that dispossessed its existing custodians.', caveat: 'District symbol only. Surviving sandstone buildings are later than the first settlement and are not all represented as structures from 1788.', sources: ['sydney-rocks-history'] },
    { id: 'sydney-botanic', name: 'Royal Botanic Garden Sydney', coordinates: [151.2165, -33.8642], visibleFrom: 1816, model: 'park', dateLabel: 'Established 1816', description: 'A colonial scientific garden on Gadigal Country became a lasting harbour-side institution.', caveat: 'Generic garden marker, not original planting or exact boundaries. Later scientific collections are not assumed to have existed at establishment.', sources: ['sydney-botanic-gardens'] },
    { id: 'sydney-barracks', name: 'Hyde Park Barracks', coordinates: [151.2128, -33.8695], visibleFrom: 1819, model: 'district', dateLabel: 'Opened 1819; successive institutional uses', description: 'Convict accommodation later became an immigration depot, asylum and government complex before its museum use.', caveat: 'Institutional site symbol, not an architectural replica or a claim that every later use existed in 1819.', sources: ['sydney-barracks-mhnsw'] },
    { id: 'sydney-first-railway', name: 'Original Sydney railway terminal area', coordinates: [151.205, -33.884], visibleFrom: 1855, model: 'district', dateLabel: 'First NSW railway opened 26 September 1855', description: 'The original terminus stood south of Devonshire Street, near but distinct from today\'s Central Station.', caveat: 'Approximate historical site marker, not the modern Central Station building or present Redfern Station. The original station structure is not shown as surviving.', sources: ['sydney-rail-mhnsw'] },
    { id: 'sydney-harbour-bridge', name: 'Sydney Harbour Bridge', coordinates: [151.2108, -33.8523], visibleFrom: 1932, model: 'bridge', dateLabel: 'Opened 19 March 1932', description: 'The steel arch carries a major connection between the central city and North Shore.', caveat: 'Original generic bridge miniature, not a replica of the arch, pylons or traffic layout. Absent from all pre-1932 chapters.', sources: ['sydney-bridge-transport'] },
    { id: 'sydney-opera-house', name: 'Sydney Opera House', coordinates: [151.2153, -33.8568], visibleFrom: 1973, model: 'opera', dateLabel: 'Opened 20 October 1973', description: 'A major performing-arts complex transformed the headland after a fourteen-year building programme.', caveat: 'Generic abstract roof composition, not Utzon\'s architecture or an exact structural model. The current building is never projected into earlier harbour views.', sources: ['sydney-opera-nfsa'] },
    { id: 'sydney-barangaroo', name: 'Barangaroo Reserve', coordinates: [151.202, -33.857], visibleFrom: 2015, model: 'park', dateLabel: 'Opened 2015', description: 'A former industrial waterfront became a designed public landscape of sandstone, native planting and paths.', caveat: 'Symbolic modern park. This manufactured headland is not a surveyed restoration of the pre-colonial shoreline.', sources: ['sydney-barangaroo'] },
  ],
  water: [
    { name: 'Sydney Harbour - schematic central water', kind: 'area', points: [[151.196, -33.852], [151.205, -33.85], [151.215, -33.849], [151.229, -33.849], [151.241, -33.842], [151.255, -33.827], [151.272, -33.821], [151.278, -33.837], [151.267, -33.85], [151.251, -33.854], [151.234, -33.858], [151.223, -33.857], [151.219, -33.855], [151.217, -33.853], [151.214, -33.855], [151.214, -33.859], [151.21, -33.859], [151.207, -33.854], [151.196, -33.856], [151.196, -33.852]] },
    { name: 'Parramatta River and western harbour - schematic', kind: 'river', widthKm: 0.45, points: [[151.114, -33.837], [151.128, -33.833], [151.14, -33.838], [151.15, -33.845], [151.159, -33.847], [151.166, -33.839], [151.179, -33.839], [151.187, -33.847], [151.198, -33.853], [151.207, -33.853]] },
    { name: 'Darling Harbour - schematic inlet', kind: 'area', points: [[151.198, -33.852], [151.202, -33.853], [151.201, -33.861], [151.203, -33.868], [151.201, -33.874], [151.197, -33.874], [151.196, -33.867], [151.195, -33.861], [151.198, -33.852]] },
  ],
  districts: [
    { name: 'Gadigal harbour Country - interpretive seed', coordinates: [151.215, -33.859], radiusKm: 1.5, visibleFrom: 1600 },
    { name: 'The Rocks and Sydney Cove', coordinates: [151.209, -33.859], radiusKm: 0.65, visibleFrom: 1788 },
    { name: 'Macquarie Street institutions', coordinates: [151.213, -33.867], radiusKm: 0.7, visibleFrom: 1855 },
    { name: 'Railway and southern city', coordinates: [151.204, -33.884], radiusKm: 1, visibleFrom: 1855 },
    { name: 'North Shore bridge approaches', coordinates: [151.21, -33.845], radiusKm: 1, visibleFrom: 1932 },
  ],
  sources: [
    { id: 'sydney-gadi-museum', title: 'GADI exhibition: Aboriginal culture and the Country now known as Sydney', publisher: 'Australian Museum, with local Aboriginal Elders and communities', url: 'https://australian.museum/about/history/exhibitions/gadi/' },
    { id: 'sydney-first-fleet-library', title: 'First Fleet journals', publisher: 'State Library of New South Wales', url: 'https://www.sl.nsw.gov.au/stories/first-fleet-journals' },
    { id: 'sydney-rocks-history', title: 'Our story: The Rocks', publisher: 'Placemaking NSW / The Rocks', url: 'https://www.therocks.com/our-story' },
    { id: 'sydney-barracks-mhnsw', title: 'A short history of the Hyde Park Barracks', publisher: 'Museums of History NSW', url: 'https://mhnsw.au/stories/museum-stories/short-history-hyde-park-barracks/' },
    { id: 'sydney-rail-mhnsw', title: '26 September 1855: first railway line opened', publisher: 'Museums of History NSW', url: 'https://mhnsw.au/stories/on-this-day/26-september-1855/' },
    { id: 'sydney-bridge-transport', title: 'A short history of the Sydney Harbour Bridge', publisher: 'Transport for NSW', url: 'https://www.transport.nsw.gov.au/operations/roads-and-waterways/environment-and-heritage/heritage/a-short-history-of-sydney-harbour' },
    { id: 'sydney-opera-nfsa', title: 'Landmark: construction of the Sydney Opera House', publisher: 'National Film and Sound Archive of Australia', url: 'https://www.nfsa.gov.au/collection/item/landmark-construction-sydney-opera-house' },
    { id: 'sydney-botanic-gardens', title: 'About us: Royal Botanic Garden Sydney, established 1816', publisher: 'Botanic Gardens of Sydney', url: 'https://www.botanicgardens.org.au/about-us' },
    { id: 'sydney-barangaroo', title: 'The creation of Barangaroo Reserve', publisher: 'Infrastructure NSW / Barangaroo', url: 'https://www.barangaroo.com/past-present-future/barangaroo-reserve' },
    { id: 'sydney-abs-2021', title: '2021 Greater Sydney: Census All persons QuickStats (1GSYD)', publisher: 'Australian Bureau of Statistics', url: 'https://www.abs.gov.au/census/find-census-data/quickstats/2021/1GSYD' },
  ],
}
