import type { WorldCity } from '../types'

export const city: WorldCity = {
  id: 'tokyo',
  name: 'Tokyo',
  country: 'Japan',
  continent: 'Asia',
  tagline: 'From Edo waterways to a metropolis rebuilt more than once.',
  center: [139.767, 35.683],
  mapBounds: [139.48, 35.48, 140.03, 35.9],
  historicalBounds: [139.65, 35.59, 139.88, 35.77],
  reconstructionNote: 'Original generic symbolic miniatures, not architectural replicas. Density and district radii are illustrative, not measured historical footprints. Viewing bounds include Haneda Airport but are not Tokyo Metropolis borders. Hand-traced Sumida and bay geometry is for orientation only; reclamation and historical shorelines are not reconstructed. Modern is the 2025 endpoint label, with individually dated evidence rather than a frozen 2025 population.',
  chapters: [
    {
      year: 1603,
      label: 'Edo and the shogunate',
      title: 'A political centre beside the waterways',
      description: 'Tokugawa Ieyasu established his shogunate in Edo in 1603. The emperor still resided in Kyoto, so Edo\'s new political importance should not be confused with Tokyo\'s later imperial role. Bridges, waterways and growing merchant districts supported the seat of military government. Asakusa already had a much older religious history, although its surviving main hall is a twentieth-century reconstruction.',
      life: 'Officials, craftspeople, merchants and labourers supported an expanding government town. Water transport and bridge approaches brought trade into daily contact with political authority; social rank strongly shaped where people lived and worked.',
      changes: ['Edo becomes the seat of Tokugawa military government, distinct from imperial Kyoto.', 'The first Nihonbashi crossing anchors an increasingly important commercial district.'],
      sources: ['tokyo-government-history', 'tokyo-nihonbashi', 'tokyo-sensoji-history'],
      stats: [
        { label: 'Population', value: 'Not reliably known', scope: 'Edo in 1603; the cited history gives no comparable count for this founding-year snapshot', asOf: '1603', source: 'tokyo-government-history' },
        { label: 'Government institution', value: 'Tokugawa shogunate', scope: 'Military government headquartered in Edo; imperial court remained in Kyoto', asOf: 'Established in Edo in 1603', source: 'tokyo-government-history' },
      ],
      focus: [139.757, 35.687],
      spanKm: 5,
      density: 0.2,
    },
    {
      year: 1750,
      label: 'A vast Edo city',
      title: 'Markets, highways and public institutions',
      description: 'By the middle of the eighteenth century, Edo was among the world\'s largest cities. Nihonbashi connected urban commerce to the main highways, while Asakusa attracted worshippers and entertainment. Government responses to fire and public health developed alongside this growth. The population figure is the metropolitan government\'s approximate historical benchmark for 1721, not a modern census or a count taken in 1750.',
      life: 'Market streets, river deliveries and pilgrimages made different parts of Edo interdependent. Fire prevention mattered in a densely built city, while public institutions began addressing some of the needs created by concentrated urban life.',
      changes: ['Nihonbashi links the city to the five main Edo-period highways.', 'Organised firefighting and a government free hospital become part of urban administration.'],
      sources: ['tokyo-government-history', 'tokyo-nihonbashi'],
      stats: [
        { label: 'Population benchmark', value: 'About 1.3 million', scope: 'Edo; approximate historical figure in the Tokyo government timeline', asOf: '1721 benchmark, not a 1750 count', source: 'tokyo-government-history' },
        { label: 'Main highway routes', value: '5', scope: 'Edo-period trunk-road network starting from Nihonbashi', asOf: 'Edo period, seventeenth-eighteenth centuries', source: 'tokyo-nihonbashi' },
      ],
      focus: [139.774, 35.685],
      spanKm: 6,
      density: 0.55,
    },
    {
      year: 1889,
      label: 'Meiji Tokyo',
      title: 'An imperial capital takes new forms',
      description: 'Edo became Tokyo in 1868 as imperial rule replaced the shogunate. Telegraphs, railways, public parks and new government institutions changed both the physical city and its relationship with the country. In 1889 Tokyo City was organised into fifteen wards. That municipal geography is not the present twenty-three-ward system or the larger Tokyo Metropolis used for today\'s population benchmark.',
      life: 'Rail journeys, new public institutions and changing fashions entered daily life alongside older trades and neighbourhood customs. Ueno became a place for public recreation and exhibitions, while government and commerce reshaped former elite districts.',
      changes: ['The imperial move and renaming of Edo establish Tokyo\'s new national role.', 'Rail access, public parks and a fifteen-ward municipality reorganise the growing capital.'],
      sources: ['tokyo-government-history', 'tokyo-ueno'],
      stats: [
        { label: 'Municipal wards', value: '15', scope: 'Tokyo City at its establishment; not today\'s 23 special wards', asOf: '1889', source: 'tokyo-government-history' },
        { label: 'Railway institution', value: 'Shimbashi-Yokohama line', scope: 'Japan\'s first railway, linking Tokyo to the treaty port', asOf: 'Opened in 1872', source: 'tokyo-government-history' },
      ],
      focus: [139.762, 35.684],
      spanKm: 7,
      density: 0.6,
    },
    {
      year: 1923,
      label: 'Earthquake and rebuilding',
      title: 'A regional disaster changes the capital',
      description: 'The Great Kanto Earthquake struck on 1 September 1923. Earthquake damage and fire devastated Tokyo and other communities across the region. Reconstruction changed roads and public infrastructure, although the full proposed programme exceeded available funds. The population shown belongs to Tokyo prefecture in the 1920 census; the earthquake magnitude describes the regional event, not a measurement of damage at a particular Tokyo landmark.',
      life: 'Survivors confronted lost homes, interrupted work and damaged services. Recovery required housing and infrastructure as well as rebuilding individual monuments; the scene is not a building-by-building damage map or a complete account of suffering.',
      changes: ['Earthquake and fire destroy extensive parts of Tokyo and the surrounding region.', 'Reconstruction planning establishes important elements of the later transport and street network.'],
      sources: ['tokyo-government-history', 'tokyo-earthquake-jma'],
      stats: [
        { label: 'Population benchmark', value: '3,699,428', scope: 'Tokyo-fu, the historical prefecture; not Tokyo-shi or modern Tokyo Metropolis', asOf: '1920 census', source: 'tokyo-government-history' },
        { label: 'Earthquake magnitude', value: '7.9', scope: 'Great Kanto earthquake; Japan Meteorological Agency magnitude, not local intensity', asOf: '1 September 1923', source: 'tokyo-earthquake-jma' },
      ],
      focus: [139.793, 35.699],
      spanKm: 7,
      density: 0.4,
    },
    {
      year: 1964,
      label: 'Post-war transformation',
      title: 'Mass transit and an Olympic metropolis',
      description: 'War had again devastated Tokyo in 1945. Recovery and rapid economic growth brought new industries, household technologies and immense demand for movement. Tokyo Tower and the rebuilt Senso-ji main hall both date from 1958. The 1964 Olympics and the opening of the Shinkansen signalled another transformation, but the pollution and social costs of rapid growth also belong to this story.',
      life: 'New appliances and television changed domestic routines while expanding transport connected homes and workplaces. Post-war rebuilding was visible in both sacred and commercial landmarks; prosperity brought new possibilities without eliminating the strains of a large city.',
      changes: ['Post-war reconstruction creates new structures on older religious and urban sites.', 'The Olympics and Shinkansen make rapid-growth Tokyo internationally visible.'],
      sources: ['tokyo-government-history', 'tokyo-tower', 'tokyo-sensoji-hall'],
      stats: [
        { label: 'Population milestone', value: 'Over 10 million', scope: 'Tokyo Metropolis; historical government milestone, not a 1964 census', asOf: '1962', source: 'tokyo-government-history' },
        { label: 'Tokyo Tower height', value: '333 m', scope: 'Broadcasting tower in Shiba; not Tokyo Skytree', asOf: 'Completed in 1958', source: 'tokyo-tower' },
      ],
      focus: [139.726, 35.674],
      spanKm: 8,
      density: 0.8,
    },
    {
      year: 2025,
      label: 'Modern - latest dated evidence',
      title: 'Many centres, one connected region',
      description: 'Modern Tokyo is polycentric: historic districts coexist with major interchange stations, waterfront redevelopment and newer vertical landmarks. Haneda connects the metropolis to other regions, while the Sumida still gives the eastern city a legible axis. This modern chapter uses the government profile updated in 2026, with an explicitly dated October 2025 population estimate for Tokyo Metropolis, not the entire greater urban region.',
      life: 'Residents move through an extensive public-transport network and neighbourhoods with very different histories. Older shopping streets, temples, parks and waterfront spaces remain active parts of a city continually adapting to demographic change and disaster risk.',
      changes: ['Tokyo Skytree adds a new eastern landmark without replacing older urban centres.', 'Disaster resilience and connectivity remain central to the mature metropolis.'],
      sources: ['tokyo-government-history', 'tokyo-skytree'],
      stats: [
        { label: 'Population estimate', value: '14.273 million', scope: 'Tokyo Metropolis, including Tama and the islands; not the 23 wards alone or Greater Tokyo', asOf: '1 October 2025 estimate, government profile updated April 2026', source: 'tokyo-government-history' },
        { label: 'Tokyo Skytree height', value: '634 m', scope: 'Broadcasting tower at Oshiage', asOf: 'Opened in 2012', source: 'tokyo-skytree' },
      ],
      focus: [139.771, 35.682],
      spanKm: 12,
      density: 1,
    },
  ],
  places: [
    { id: 'tokyo-sensoji-site', name: 'Senso-ji historic precinct', coordinates: [139.7967, 35.7148], visibleFrom: 628, visibleUntil: 1958, model: 'district', dateLabel: 'Foundation tradition: 628; successive later buildings', description: 'Asakusa\'s temple tradition long predates the Tokugawa city and became an important focus of Edo religious life.', caveat: 'Historic site marker, not a seventh-century or Edo-period replica. The current main hall appears separately only from 1958; 628 is the temple\'s foundation tradition.', sources: ['tokyo-sensoji-history', 'tokyo-sensoji-hall'] },
    { id: 'tokyo-nihonbashi-site', name: 'Early Nihonbashi crossing', coordinates: [139.7745, 35.6841], visibleFrom: 1603, visibleUntil: 1911, model: 'district', dateLabel: 'First bridge 1603; successive wooden bridges', description: 'The crossing became the commercial starting point for the main routes out of Edo.', caveat: 'Crossing-area symbol only. The stone bridge now on this site did not exist in the Edo chapters.', sources: ['tokyo-nihonbashi'] },
    { id: 'tokyo-nihonbashi-bridge', name: 'Nihonbashi stone bridge', coordinates: [139.7745, 35.6841], visibleFrom: 1911, model: 'bridge', dateLabel: 'Present stone bridge completed 1911', description: 'The surviving crossing marks an older commercial centre while belonging to a later rebuilding.', caveat: 'Generic bridge, not a replica; the later overhead expressway is not modelled as part of the 1911 structure.', sources: ['tokyo-nihonbashi'] },
    { id: 'tokyo-ueno', name: 'Ueno Park', coordinates: [139.773, 35.714], visibleFrom: 1873, model: 'park', dateLabel: 'Public park established 1873', description: 'Public recreation and cultural institutions gave Ueno a new role in Meiji Tokyo.', caveat: 'Symbolic park cluster, not surveyed landscaping. Later museum buildings are not backdated to the park\'s establishment.', sources: ['tokyo-ueno'] },
    { id: 'tokyo-station', name: 'Tokyo Station', coordinates: [139.7671, 35.6812], visibleFrom: 1914, model: 'district', dateLabel: 'Marunouchi station building completed 1914', description: 'The red-brick terminus made the Marunouchi area a major gateway to the capital.', caveat: 'Station-area marker rather than a replica of the 1914 building or its later restoration; underground infrastructure is not reconstructed.', sources: ['tokyo-government-history'] },
    { id: 'tokyo-tower', name: 'Tokyo Tower', coordinates: [139.7454, 35.6586], visibleFrom: 1958, model: 'tower', dateLabel: 'Completed 1958', description: 'The 333-metre broadcasting tower became a prominent symbol of post-war Tokyo.', caveat: 'Original generic tower miniature, not the real lattice design. It is never shown in Edo or pre-war chapters.', sources: ['tokyo-tower'] },
    { id: 'tokyo-sensoji-hall', name: 'Senso-ji rebuilt main hall', coordinates: [139.7967, 35.7148], visibleFrom: 1958, model: 'temple', dateLabel: 'Present main hall rebuilt 1958', description: 'The post-war hall renewed a much older place of worship after the destruction of 1945.', caveat: 'Generic temple symbol, not an architectural replica. Its modern construction date is distinct from the temple\'s 628 foundation tradition.', sources: ['tokyo-sensoji-history', 'tokyo-sensoji-hall'] },
    { id: 'tokyo-rainbow-bridge', name: 'Rainbow Bridge', coordinates: [139.763, 35.6365], visibleFrom: 1993, model: 'bridge', dateLabel: 'Opened 1993', description: 'The harbour crossing connects the established city to its developed waterfront.', caveat: 'Symbolic bridge, not exact engineering geometry. The bay outline does not reconstruct successive reclamation projects.', sources: ['tokyo-government-history'] },
    { id: 'tokyo-skytree', name: 'Tokyo Skytree', coordinates: [139.8107, 35.7101], visibleFrom: 2012, model: 'tower', dateLabel: 'Opened 2012', description: 'A 634-metre broadcasting tower gives the eastern city a contemporary landmark near the Sumida.', caveat: 'Generic tapered tower, not an architectural replica; deliberately unavailable before 2012.', sources: ['tokyo-skytree'] },
  ],
  water: [
    { name: 'Sumida River - schematic course', kind: 'river', widthKm: 0.18, points: [[139.782, 35.755], [139.796, 35.744], [139.806, 35.73], [139.806, 35.721], [139.8, 35.712], [139.792, 35.704], [139.789, 35.696], [139.789, 35.688], [139.798, 35.681], [139.794, 35.673], [139.785, 35.665], [139.776, 35.65]] },
    { name: 'Tokyo Bay - schematic inner bay', kind: 'area', points: [[139.748, 35.634], [139.759, 35.643], [139.772, 35.65], [139.796, 35.646], [139.821, 35.646], [139.84, 35.622], [139.87, 35.604], [139.918, 35.59], [139.92, 35.52], [139.81, 35.51], [139.772, 35.55], [139.757, 35.589], [139.748, 35.634]] },
  ],
  districts: [
    { name: 'Edo government core', coordinates: [139.756, 35.687], radiusKm: 1.1, visibleFrom: 1603 },
    { name: 'Nihonbashi commerce', coordinates: [139.775, 35.685], radiusKm: 0.8, visibleFrom: 1603 },
    { name: 'Asakusa', coordinates: [139.795, 35.713], radiusKm: 0.9, visibleFrom: 1603 },
    { name: 'Ueno public institutions', coordinates: [139.773, 35.714], radiusKm: 0.8, visibleFrom: 1889 },
    { name: 'Shinjuku and western growth', coordinates: [139.704, 35.691], radiusKm: 1.5, visibleFrom: 1964 },
  ],
  sources: [
    { id: 'tokyo-government-history', title: 'Tokyo\'s History, Geography, and Population', publisher: 'Tokyo Metropolitan Government', url: 'https://www.english.metro.tokyo.lg.jp/w/000-101-007591' },
    { id: 'tokyo-nihonbashi', title: 'Nihonbashi Bridge', publisher: 'Tokyo Convention & Visitors Bureau / GO TOKYO', url: 'https://www.gotokyo.org/en/spot/44/index.html' },
    { id: 'tokyo-sensoji-history', title: 'History of Senso-ji', publisher: 'Senso-ji Temple', url: 'https://www.senso-ji.jp/english/' },
    { id: 'tokyo-sensoji-hall', title: 'Main Hall: destruction and 1958 rebuilding', publisher: 'Senso-ji Temple', url: 'https://www.senso-ji.jp/guide/guide04.html' },
    { id: 'tokyo-ueno', title: 'Ueno Park', publisher: 'Tokyo Convention & Visitors Bureau / GO TOKYO', url: 'https://www.gotokyo.org/jp/spot/482/index.html' },
    { id: 'tokyo-tower', title: 'Tokyo Tower', publisher: 'Tokyo Convention & Visitors Bureau / GO TOKYO', url: 'https://www.gotokyo.org/en/spot/4/index.html' },
    { id: 'tokyo-skytree', title: 'Explore Tokyo Skytree and around', publisher: 'Tokyo Convention & Visitors Bureau / GO TOKYO', url: 'https://www.gotokyo.org/en/story/walks-and-tours/tokyo-skytree-and-around/index.html' },
    { id: 'tokyo-earthquake-jma', title: 'The 1923 Kanto earthquake: overview', publisher: 'Japan Meteorological Agency', url: 'https://www.data.jma.go.jp/eqev/data/1923_09_01_kantoujishin/gaiyo.html' },
  ],
}
