import { expect, test } from '@playwright/test'

test('era explorer, tours and cited field notes work across the timeline', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/?year=1591&view=atlas')
  await expect(page).toHaveTitle('Hyderabad 1591 · Through Time')
  await expect(page.locator('canvas')).toBeVisible({ timeout: 25_000 })
  if (testInfo.project.name === 'mobile') await page.getByRole('button', { name: /Read this chapter/ }).click()
  await expect(page.locator('.year-display')).toHaveText('1591CE')
  await page.getByRole('button', { name: /Explore this chapter/ }).click()
  await expect(page.locator('.field-note-panel')).toContainText('Charminar')
  await expect(page).toHaveURL(/place=charminar/)
  await page.getByRole('button', { name: 'Close tour', exact: true }).click()
  await page.getByRole('button', { name: 'Close field note', exact: true }).click()
  await page.getByRole('button', { name: /2025:/ }).click()
  await expect(page).toHaveTitle('Hyderabad 2025 · Through Time')
  if (testInfo.project.name === 'mobile') await page.getByRole('button', { name: /Read this chapter/ }).click()
  await page.getByRole('button', { name: /Explore places/ }).click()
  await page.getByLabel('Find a place in 2025').fill('Cyber')
  await page.locator('.place-row').filter({ hasText: 'Cyber Towers' }).click()
  await expect(page.locator('.field-note-panel')).toContainText('Cyber Towers')
  await page.getByRole('button', { name: 'Read the source record' }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await expect(dialog).toContainText('Not a photograph of the past.')
  await expect(dialog.locator('.source-list').first().getByRole('link').first()).toHaveAttribute('href', /^https:/)
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  expect(errors).toEqual([])
})

test('navigation, atmosphere and map layers respond without page errors', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/?year=1948&view=atlas')
  await expect(page.locator('canvas')).toBeVisible({ timeout: 25_000 })
  await page.getByRole('button', { name: 'After dark', exact: true }).click()
  await expect(page.getByRole('button', { name: 'After dark', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Layers', exact: true }).click()
  await page.getByLabel('Interpretive city fabric', { exact: true }).uncheck()
  await expect(page.getByLabel('Interpretive city fabric', { exact: true })).not.toBeChecked()
  await page.getByRole('button', { name: 'Layers', exact: true }).click()
  await page.getByRole('button', { name: 'Street view', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Move forward', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Move forward', exact: true }).click()
  await page.getByRole('button', { name: 'Reset aerial view', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Orbit', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('deep links respect chronology and era changes do not retain stale search', async ({ page }, testInfo) => {
  await page.goto('/?year=1518&place=cyber-towers&view=atlas')
  await expect(page).toHaveURL(/year=1518&view=atlas$/)
  await expect(page.locator('.field-note-panel')).toHaveCount(0)
  await expect(page.locator('.mini-map').getByRole('button', { name: 'Locate Charminar', exact: true })).toHaveCount(0)
  await page.goto('/?year=2025&place=cyber-towers&view=atlas')
  await expect(page.locator('.field-note-panel')).toContainText('Cyber Towers')
  await page.getByRole('button', { name: 'Close field note', exact: true }).click()
  if (testInfo.project.name === 'mobile') await page.getByRole('button', { name: /Read this chapter/ }).click()
  await page.getByRole('button', { name: /Explore places/ }).click()
  await page.getByLabel('Find a place in 2025').fill('Cyber')
  await page.getByRole('button', { name: /1518:/ }).click()
  await expect(page.getByLabel('Find a place in 1518')).toHaveValue('')
  await expect(page.locator('.place-row')).toHaveCount(1)
  await expect(page.locator('.place-row')).toContainText('Golconda Fort')
})

test('a pinned monument stays in view while its historical condition changes', async ({ page }) => {
  await page.goto('/?year=1591&place=golconda&view=atlas')
  await expect(page.locator('.monument-time-note')).toContainText('A working fortified city')
  await page.getByRole('button', { name: 'Keep this place as time changes', exact: true }).click()
  await page.getByRole('button', { name: /2025:/ }).click()
  await expect(page).toHaveURL(/year=2025&place=golconda/)
  await expect(page.locator('.monument-time-note')).toContainText('Standing walls, open ruins')
  await expect(page.locator('canvas')).toHaveAttribute('data-monument-fabric', /golconda:ruin/)
  await page.getByRole('button', { name: 'Following this place through time', exact: true }).click()
  await page.getByRole('button', { name: /1518:/ }).click()
  await expect(page.locator('.field-note-panel')).toHaveCount(0)
})

test('city life enters populated neighbourhoods and street navigation moves the camera', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/?year=2025&view=atlas')
  const canvas = page.locator('canvas')
  await expect(canvas).toHaveAttribute('data-city-districts', '25', { timeout: 30_000 })
  expect(Number(await canvas.getAttribute('data-city-buildings'))).toBeGreaterThan(1000)
  if (testInfo.project.name === 'mobile') await page.getByRole('button', { name: /Read this chapter/ }).click()
  await page.getByRole('button', { name: 'City life', exact: true }).click()
  await expect(page.locator('.life-vignette')).toContainText('RECONSTRUCTED STREET SCENE')
  await expect(page.locator('.district-row')).toHaveCount(25)
  await page.locator('.district-row').filter({ hasText: 'Charminar & the old city' }).click()
  await expect(page.locator('.district-hud')).toContainText('Charminar & the old city')
  await expect.poll(async () => Number((await canvas.getAttribute('data-camera-position'))?.split(',')[1]), { timeout: 30_000 }).toBeLessThan(.3)
  await expect(canvas).toHaveAttribute('data-district', 'old-city')
  await expect(page.locator('.discovery-count')).toHaveText('1 / 25')
  await canvas.focus()
  const before = await canvas.getAttribute('data-camera-position')
  await page.keyboard.press('w')
  await expect.poll(() => canvas.getAttribute('data-camera-position')).not.toBe(before)
  await page.getByRole('button', { name: 'Reset aerial view', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Orbit', exact: true })).toHaveAttribute('aria-pressed', 'true')
  expect(errors).toEqual([])
})

test('modern minimap markers remain individually selectable', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'Same deterministic marker layout on mobile')
  await page.goto('/?year=2025&view=atlas')
  await page.locator('.mini-map').getByRole('button', { name: 'Locate Charminar', exact: true }).click()
  await expect(page.locator('.field-note-panel')).toContainText('Charminar')
  await page.getByRole('button', { name: 'Minimize field note', exact: true }).click()
  await expect(page.locator('.field-note-panel')).toHaveClass(/is-collapsed/)
  await page.getByRole('button', { name: 'Expand field note', exact: true }).click()
  await expect(page.locator('.field-note-content')).toBeVisible()
})

test('an era expedition rewards exploration and learning, then survives a reload', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/?year=1591&view=atlas')
  if (testInfo.project.name === 'mobile') await page.getByRole('button', { name: /Read this chapter/ }).click()
  await page.getByRole('button', { name: /Challenges/ }).click()
  const cards = page.locator('.challenge-card')
  await cards.nth(0).getByRole('button', { name: /Scout this place/ }).click()
  await page.getByRole('button', { name: 'Close field note', exact: true }).click()
  await expect(page.locator('.expedition-hud')).toContainText('1591 EXPEDITION · 1/3')
  await page.locator('.expedition-next').click()
  await page.getByRole('button', { name: 'Close field note', exact: true }).click()
  await expect(page.locator('.expedition-hud')).toContainText('Make a discovery')
  await page.locator('.expedition-next').click()
  await cards.nth(2).getByRole('button', { name: 'Cyber Towers and an IT ring road', exact: true }).click()
  await expect(page.locator('.quiz-feedback')).toContainText('no penalty')
  await expect(page.getByRole('progressbar', { name: 'Era expedition progress' })).toHaveAttribute('value', '2')
  await cards.nth(2).getByRole('button', { name: 'Four cardinal avenues around Charminar', exact: true }).click()
  await expect(page.locator('.era-badge')).toContainText('Founding-city explorer')
  await page.reload()
  if (testInfo.project.name === 'mobile') await page.getByRole('button', { name: /Read this chapter/ }).click()
  await page.getByRole('button', { name: /Challenges/ }).click()
  await expect(page.locator('.era-badge')).toContainText('Founding-city explorer')
  await expect(page.locator('.expedition-total')).toHaveText('3 / 24 discoveries · 1 / 8 chapter badges')
  expect(errors).toEqual([])
})

test('city statistics disclose benchmark dates, boundaries and missing evidence', async ({ page }, testInfo) => {
  await page.goto('/?year=1908&view=atlas')
  if (testInfo.project.name === 'mobile') await page.getByRole('button', { name: /Read this chapter/ }).click()
  const stats = page.getByRole('region', { name: 'City statistics for 1908' })
  await expect(stats).toContainText('Population · 1901')
  await expect(stats).toContainText('4,48,466')
  await stats.locator('.population-stat summary').click()
  await expect(stats).toContainText('Secunderabad and Bolarum cantonments')
  await expect(stats.getByRole('link', { name: /Read the population source/ })).toHaveAttribute('href', 'https://archive.org/details/in.ernet.dli.2015.63122')
  await page.getByRole('button', { name: /1948:/ }).click()
  await expect(page.locator('.city-stats')).toContainText('Population · 1941')
  await expect(page.locator('.city-stats')).toContainText('7,39,159')
  await page.getByRole('button', { name: /2025:/ }).click()
  await expect(page.locator('.city-stats')).toContainText('Population · 2011')
  await expect(page.locator('.city-stats')).toContainText('NOT 2025 population')
  await page.getByRole('button', { name: /1518:/ }).click()
  await expect(page.locator('.city-stats')).toContainText('73 years')
  await expect(page.locator('.city-stats')).toContainText('Not established')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('the guide still works without WebGL', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'Fallback is renderer-independent')
  await page.addInitScript(() => {
    const original = HTMLCanvasElement.prototype.getContext
    Object.defineProperty(HTMLCanvasElement.prototype, 'getContext', {
      value(this: HTMLCanvasElement, contextId: string, ...args: unknown[]) {
        if (contextId.startsWith('webgl')) return null
        return Reflect.apply(original, this, [contextId, ...args])
      },
    })
  })
  await page.goto('/?year=1518&view=atlas')
  await expect(page.getByRole('heading', { name: 'A different way to explore.' })).toBeVisible()
  await page.locator('.large-map').getByRole('button', { name: 'Locate Golconda Fort' }).click()
  await expect(page.locator('.field-note-panel')).toContainText('Golconda Fort')
  await page.getByRole('button', { name: /2025:/ }).click()
  await expect(page).toHaveTitle('Hyderabad 2025 · Through Time')
})

test('period stories link back to era-appropriate places', async ({ page }, testInfo) => {
  await page.goto('/?year=1591&view=atlas')
  if (testInfo.project.name === 'mobile') await page.getByRole('button', { name: /Read this chapter/ }).click()
  await page.getByRole('button', { name: 'City life', exact: true }).click()
  const stories = page.getByRole('region', { name: 'Stories and interesting facts for 1591' })
  await expect(stories.locator('details')).toHaveCount(2)
  await stories.locator('summary').first().click()
  await expect(stories).toContainText('mosque')
  await stories.getByRole('button', { name: 'Explore Charminar', exact: true }).first().click()
  await expect(page.locator('.field-note-panel')).toContainText('Charminar')
})

test('an unmarked map point is navigable and shareable in the illustrated atlas', async ({ page }) => {
  await page.goto('/?year=1591&view=atlas')
  const mini = page.locator('.mini-map')
  await mini.locator('svg').click({ position: { x: 90, y: 70 } })
  await expect(page.locator('.destination-hud')).toBeVisible()
  const url = new URL(page.url())
  expect(url.searchParams.has('lat')).toBe(true)
  expect(url.searchParams.has('lon')).toBe(true)
  expect(url.searchParams.has('place')).toBe(false)
  await page.reload()
  await expect(page.locator('.destination-hud')).toBeVisible()
})
