import { expect, test } from '@playwright/test'

test.describe('live geographic providers', () => {
  test.skip(process.env.ATLAS_LIVE_MAPS !== '1', 'Set ATLAS_LIVE_MAPS=1 to exercise public geographic services')
  test.setTimeout(120_000)

  test('latest streets support airport travel, arbitrary coordinates and a shareable view', async ({ page }, testInfo) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    await page.goto('/?year=2025&place=cyber-towers&scoutTheme=light')
    const canvas = page.locator('.geographic-scene canvas')
    await expect(canvas).toHaveAttribute('data-ready', 'true', { timeout: 60_000 })
    await expect(canvas).toHaveAttribute('data-terrain', 'non-dated-reference')
    await expect.poll(async () => Number(await canvas.getAttribute('data-mapped-buildings')), { timeout: 30_000 }).toBeGreaterThan(0)
    await page.screenshot({ path: testInfo.outputPath('2025-mapped-buildings.png') })
    await page.getByRole('button', { name: /Expand city map/ }).click()
    const dialog = page.getByRole('dialog', { name: 'Explore the whole city' })
    await expect(dialog).toBeVisible()
    await dialog.getByLabel('Find a landmark, place or coordinates').fill('Airport')
    await dialog.getByRole('button', { name: /Rajiv Gandhi International Airport/ }).click()
    await expect(dialog).toBeHidden()
    await expect(page.locator('.destination-hud')).toContainText('Rajiv Gandhi International Airport')
    await expect.poll(async () => Number(await canvas.getAttribute('data-camera-latitude')), { timeout: 30_000 }).toBeCloseTo(17.23, 3)
    await expect(canvas).toHaveAttribute('data-tiles-loaded', 'true', { timeout: 30_000 })
    await page.screenshot({ path: testInfo.outputPath('2025-airport.png') })
    await page.getByRole('button', { name: /Expand city map/ }).click()
    await dialog.getByLabel('Find a landmark, place or coordinates').fill('17.4123, 78.3567')
    await dialog.getByRole('button', { name: 'Go', exact: true }).click()
    await expect.poll(async () => Number(await canvas.getAttribute('data-camera-longitude')), { timeout: 30_000 }).toBeCloseTo(78.3567, 3)
    await expect(page).toHaveURL(/lon=78.356700/)
    await expect(page).toHaveURL(/lat=17.412300/)
    await page.getByRole('button', { name: /Expand city map/ }).click()
    const overview = dialog.locator('.geographic-overview canvas')
    await expect(overview).toHaveAttribute('data-ready', 'true', { timeout: 60_000 })
    await page.screenshot({ path: testInfo.outputPath('2025-city-navigator.png') })
    const box = await overview.boundingBox()
    if (!box) throw new Error('The expanded city map has no visible bounds')
    await overview.click({ position: { x: box.width * .73, y: box.height * .63 } })
    await expect(dialog).toBeHidden()
    const chosen = new URL(page.url()).searchParams.get('lon')
    expect(chosen).not.toBe('78.356700')
    await expect.poll(async () => Number(await canvas.getAttribute('data-camera-longitude')), { timeout: 30_000 }).toBeCloseTo(Number(chosen), 3)
    await page.getByRole('button', { name: /Expand city map/ }).click()
    await dialog.getByLabel('Find a landmark, place or coordinates').fill('Salar Jung Museum')
    await dialog.getByRole('button', { name: 'Go', exact: true }).click()
    const museum = dialog.getByRole('button', { name: /^Travel to Salar Jung Museum:/ }).first()
    await expect(museum).toBeVisible({ timeout: 20_000 })
    await page.screenshot({ path: testInfo.outputPath('2025-citywide-search.png') })
    await museum.click()
    await expect(page.locator('.destination-hud')).toContainText('Salar Jung Museum')
    await expect.poll(async () => Number(await canvas.getAttribute('data-camera-latitude')), { timeout: 30_000 }).toBeCloseTo(17.3714, 3)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    expect(errors).toEqual([])
  })

  test('1998 uses its dated imagery and not current streets or the later airport', async ({ page }, testInfo) => {
    const modernRequests: string[] = []
    page.on('request', (request) => {
      if (/tiles\.openfreemap\.org|tiles\.mapterhorn\.com|photon\.komoot\.io/.test(request.url())) modernRequests.push(request.url())
    })
    await page.goto('/?year=1998&scoutTheme=light')
    const canvas = page.locator('.geographic-scene canvas')
    await expect(canvas).toHaveAttribute('data-ready', 'true', { timeout: 60_000 })
    await expect(page.locator('.geographic-scene')).toHaveAttribute('data-layer', 'satellite')
    await expect(canvas).toHaveAttribute('data-terrain', 'none')
    await page.screenshot({ path: testInfo.outputPath('1998-dated-city.png') })
    await page.getByRole('button', { name: /Expand city map/ }).click()
    const dialog = page.getByRole('dialog', { name: 'Explore the whole city' })
    await dialog.getByLabel('Find a landmark, place or coordinates').fill('airport')
    await expect(dialog.getByRole('button', { name: /Begumpet Airport/ })).toBeVisible()
    await expect(dialog.getByRole('button', { name: /Rajiv Gandhi International Airport/ })).toHaveCount(0)
    await dialog.getByRole('button', { name: /Begumpet Airport/ }).click()
    await expect.poll(async () => Number(await canvas.getAttribute('data-camera-latitude')), { timeout: 30_000 }).toBeCloseTo(17.45305556, 3)
    expect(modernRequests).toEqual([])
  })

  test('2025 satellite comparison can return to the latest street map', async ({ page }, testInfo) => {
    await page.goto('/?year=2025&layer=satellite&lat=17.23&lon=78.431944&zoom=14&scoutTheme=light')
    const scene = page.locator('.geographic-scene')
    await expect(scene).toHaveAttribute('data-layer', 'satellite')
    await expect(scene.locator('canvas')).toHaveAttribute('data-ready', 'true', { timeout: 60_000 })
    await page.screenshot({ path: testInfo.outputPath('2025-dated-airport.png') })
    await page.getByRole('button', { name: 'Layers', exact: true }).click()
    await page.getByRole('button', { name: 'Latest street map', exact: true }).click()
    await expect(scene).toHaveAttribute('data-layer', 'streets')
    await expect(scene.locator('canvas')).toHaveAttribute('data-ready', 'true', { timeout: 60_000 })
    await expect(page).not.toHaveURL(/layer=satellite/)
  })
})

test('geographic service failure is explicit and the illustrated edition remains available', async ({ page }) => {
  await page.route('https://tiles.openfreemap.org/**', (route) => route.abort('failed'))
  await page.goto('/?year=2025')
  await expect(page.locator('.map-error-panel')).toContainText('Map data could not be loaded')
  await page.getByRole('button', { name: 'Use illustrated reconstruction', exact: true }).click()
  await expect(page.locator('.geographic-scene')).toHaveCount(0)
  await expect(page.locator('canvas')).toHaveAttribute('data-city-districts', '25', { timeout: 30_000 })
  await expect(page).toHaveURL(/view=atlas/)
})
