// Generated by tools/narration/generate.mjs. Do not edit durations by hand.
export const NARRATION_AUDIO: Record<string, { src: string; duration: number }> = {
  '1518-older-stone': { src: 'narration/1518-older-stone.mp3?v=91e0feb4c838', duration: 63.09 },
  '1518-town-below-walls': { src: 'narration/1518-town-below-walls.mp3?v=fa305843aabc', duration: 62.11 },
  '1591-new-crossroads': { src: 'narration/1591-new-crossroads.mp3?v=debf4d1bb720', duration: 64.84 },
  '1591-older-crossing': { src: 'narration/1591-older-crossing.mp3?v=78afe719057b', duration: 64.11 },
  '1687-fort-and-conquest': { src: 'narration/1687-fort-and-conquest.mp3?v=e0c0a0475f6c', duration: 65.46 },
  '1687-absent-ruler': { src: 'narration/1687-absent-ruler.mp3?v=6c7e19659740', duration: 66.41 },
  '1763-inherited-skyline': { src: 'narration/1763-inherited-skyline.mp3?v=e6f8dc0bd066', duration: 64.785 },
  '1763-palace-in-the-making': { src: 'narration/1763-palace-in-the-making.mp3?v=3605fa4b0514', duration: 67.46 },
  '1908-crossroads-and-clocks': { src: 'narration/1908-crossroads-and-clocks.mp3?v=ffe6d530db1e', duration: 64.935 },
  '1908-river-and-responsibility': { src: 'narration/1908-river-and-responsibility.mp3?v=9026d002d5e3', duration: 58.98 },
  '1948-riverfront-and-reckoning': { src: 'narration/1948-riverfront-and-reckoning.mp3?v=a2773d4474fb', duration: 71.14 },
  '1948-learning-and-language': { src: 'narration/1948-learning-and-language.mp3?v=ca17c0c5c78c', duration: 67.63 },
  '1998-working-day-turns-west': { src: 'narration/1998-working-day-turns-west.mp3?v=8eed0db1a337', duration: 71.09 },
  '1998-new-statue-old-lake': { src: 'narration/1998-new-statue-old-lake.mp3?v=e6842b5d8944', duration: 60.605 },
  '2025-many-centres': { src: 'narration/2025-many-centres.mp3?v=005d5222137f', duration: 65.16 },
  '2025-what-the-future-keeps': { src: 'narration/2025-what-the-future-keeps.mp3?v=e9418146700d', duration: 68.165 },
}

export const NARRATOR = {
  label: 'Original synthetic British male narration',
  voice: 'bm_george',
  model: 'onnx-community/Kokoro-82M-v1.0-ONNX',
  license: 'Apache-2.0 model and synthesis library',
  notice: 'narration/NOTICE.txt',
} as const
