// Generated by tools/narration/generate.mjs. Do not edit durations by hand.
export const NARRATION_AUDIO: Record<string, { src: string; duration: number }> = {
  '1518-older-stone': { src: 'narration/1518-older-stone.mp3', duration: 62.915 },
  '1518-town-below-walls': { src: 'narration/1518-town-below-walls.mp3', duration: 62.11 },
  '1591-new-crossroads': { src: 'narration/1591-new-crossroads.mp3', duration: 64.615 },
  '1591-older-crossing': { src: 'narration/1591-older-crossing.mp3', duration: 63.81 },
  '1687-fort-and-conquest': { src: 'narration/1687-fort-and-conquest.mp3', duration: 65.26 },
  '1687-absent-ruler': { src: 'narration/1687-absent-ruler.mp3', duration: 66.285 },
  '1763-inherited-skyline': { src: 'narration/1763-inherited-skyline.mp3', duration: 64.41 },
  '1763-palace-in-the-making': { src: 'narration/1763-palace-in-the-making.mp3', duration: 67.46 },
  '1908-crossroads-and-clocks': { src: 'narration/1908-crossroads-and-clocks.mp3', duration: 64.935 },
  '1908-river-and-responsibility': { src: 'narration/1908-river-and-responsibility.mp3', duration: 58.98 },
  '1948-riverfront-and-reckoning': { src: 'narration/1948-riverfront-and-reckoning.mp3', duration: 71.14 },
  '1948-learning-and-language': { src: 'narration/1948-learning-and-language.mp3', duration: 67.63 },
  '1998-working-day-turns-west': { src: 'narration/1998-working-day-turns-west.mp3', duration: 71.09 },
  '1998-new-statue-old-lake': { src: 'narration/1998-new-statue-old-lake.mp3', duration: 60.605 },
  '2025-many-centres': { src: 'narration/2025-many-centres.mp3', duration: 65.16 },
  '2025-what-the-future-keeps': { src: 'narration/2025-what-the-future-keeps.mp3', duration: 67.865 },
}

export const NARRATOR = {
  label: 'Original synthetic British male narration',
  voice: 'bm_george',
  model: 'onnx-community/Kokoro-82M-v1.0-ONNX',
  license: 'Apache-2.0 model and synthesis library',
  notice: 'narration/NOTICE.txt',
} as const
