import type { Era, Landmark, Source } from './types'

export const SOURCES: Source[] = [
  { id: 'unesco', title: 'The Qutb Shahi Monuments of Hyderabad: Golconda Fort, Qutb Shahi Tombs, Charminar', publisher: 'UNESCO World Heritage Centre · Tentative List', url: 'https://whc.unesco.org/en/tentativelists/5573/' },
  { id: 'history', title: 'Hyderabad and Golconda: successive capitals', publisher: 'Deccan Heritage Foundation', url: 'https://www.deccan-heritage-foundation.org/heritage-sites/hyderabad/' },
  { id: 'conservation', title: 'Cultural development in India: conserving the Qutb Shahi royal tombs', publisher: 'Aga Khan Development Network · conservation programme', url: 'https://the.akdn/en/where-we-work/south-asia/india/cultural-development-india' },
  { id: 'urban-morphology', title: 'The Urban Morphology of Hyderabad, India: A Historical Geographic Analysis', publisher: 'Kevin B. Haynes · Western Michigan University master’s thesis · abstract verified, maps not traced', url: 'https://scholarworks.wmich.edu/masters_theses/5155/' },
  { id: 'early-painting', title: 'Muhammad Quli Qutb Shah: manuscript illustration', publisher: 'LACMA · manuscript 1610–11; illustration probably c.1700 · elite representation, not a street survey', url: 'https://collections.lacma.org/object/224364' },
  { id: 'archive-1948', title: 'Hyderabad in Color: Osmania General Hospital from Osmania Park, September 1948', publisher: 'The Deccan Archive Foundation · Jack Birns photograph caption · image not bundled', url: 'https://www.thedeccanarchive.com/projects-7' },
  { id: 'census-1901', title: 'Census of India 1901, Vol. XXII, Hyderabad, Part I: Report', publisher: 'Primary census publication · digitized copy; population passage defines the composite city boundary', url: 'https://archive.org/details/in.ernet.dli.2015.63122' },
  { id: 'census-1941', title: 'Census of India 1941, Vol. XXI, H.E.H. The Nizam’s Dominions', publisher: 'Primary census publication · Hyderabad City (M+C) table and boundary notes', url: 'https://archive.org/details/in.ernet.dli.2015.101551' },
  { id: 'population-2011', title: 'Hyderabad urban agglomeration: 2011 population', publisher: 'Census2011.co.in · independent secondary republication of provisional figures, not the Government of India', url: 'https://www.census2011.co.in/census/metropolitan/342-hyderabad.html' },
  { id: 'capital', title: 'Telangana historical background: the alternative 1769 capital-transfer date', publisher: 'Government of Telangana · RTI document (PDF)', url: 'https://cmc.telangana.gov.in/Documents/09022026151924RTI_2026.pdf' },
  { id: 'charminar', title: 'Charminar', publisher: 'Hyderabad District, Government of Telangana', url: 'https://hyderabad.telangana.gov.in/tourist-place/charminar/' },
  { id: 'golconda', title: 'Golconda Fort', publisher: 'Hyderabad District, Government of Telangana', url: 'https://hyderabad.telangana.gov.in/tourist-place/golconda-fort/' },
  { id: 'mosque', title: 'Mecca Masjid: construction from 1614 to 1693', publisher: 'Telangana Tourism', url: 'https://tourism.telangana.gov.in/attractions/mecca-masjid' },
  { id: 'bridge', title: 'Purana Pul', publisher: 'Wikipedia · secondary reference', url: 'https://en.wikipedia.org/wiki/Purana_Pul' },
  { id: 'chowmahalla', title: 'Chowmahalla Palace', publisher: 'Hyderabad District, Government of Telangana', url: 'https://hyderabad.telangana.gov.in/tourist-place/chowmahalla-palace/' },
  { id: 'lake', title: 'Hussain Sagar Lake', publisher: 'Hyderabad District, Government of Telangana', url: 'https://hyderabad.telangana.gov.in/tourist-place/hussain-sagar-lake/' },
  { id: 'court', title: 'History of the High Court', publisher: 'High Court for the State of Telangana', url: 'https://tshc.gov.in/processMenuTypes?id=257' },
  { id: 'court-building', title: 'Telangana High Court: building history', publisher: 'Wikipedia · secondary reference', url: 'https://en.wikipedia.org/wiki/Telangana_High_Court' },
  { id: 'osmania', title: 'Osmania University: origin and history', publisher: 'Osmania University · institutional chronology', url: 'https://www.osmania.ac.in/aboutus-originandhistory.php' },
  { id: 'osmania-position', title: 'Arts College geographic location', publisher: 'LatLong.net · approximate coordinate reference', url: 'https://www.latlong.net/place/osmania-university-college-of-arts-and-social-sciences-india-3019.html' },
  { id: 'residency', title: "Veeranari Chakali Ilamma Women's University: the former British Residency", publisher: 'World Monuments Fund', url: 'https://www.wmf.org/projects/veeranari-chakali-ilamma-womens-university' },
  { id: 'flood', title: 'Modernising the Urban Environment: The Musi River Flood of 1908 in Hyderabad, India', publisher: 'Benjamin B. Cohen · Environment and History 17(3), 2011 · full text may require access', url: 'https://www.jstor.org/stable/41303522' },
  { id: 'falaknuma', title: 'Taj Falaknuma Palace, Hyderabad', publisher: 'Taj Hotels · Palace history', url: 'https://www.tajhotels.com/en-in/hotels/taj-falaknuma-palace-hyderabad' },
  { id: 'hitec', title: 'Cyber Towers: building details and November 1998 opening', publisher: 'CIRIL · secondary commercial directory, not an archival opening record', url: 'https://officespace.ciril.in/Hyderabad/office-spaces/CyberTower/102' },
  { id: 'hmda', title: 'Hyderabad Metropolitan Development Authority', publisher: 'HMDA · planning jurisdiction, not historic built-up extent', url: 'https://www.hmda.gov.in/' },
]

export const LANDMARKS: Landmark[] = [
  {
    id: 'golconda', name: 'Golconda Fort', subtitle: 'The hill before the city',
    coordinates: [78.4011, 17.3833], visibleFrom: 1518, dateLabel: 'Earlier origins · Qutb Shahi expansion, 16th–17th c.',
    model: 'fort', category: 'Fortification',
    description: 'Granite, ramparts and successive fortified enclosures made Golconda the seat of the Qutb Shahi kingdom. Hyderabad was founded to its east; the older fort remained an important stronghold until the Mughal conquest in 1687.',
    caveat: 'The fort evolved over centuries. Its layered miniature is a composite silhouette, not a claim that the full surviving circuit existed in 1518.',
    sources: ['unesco', 'golconda'],
  },
  {
    id: 'tombs', name: 'Qutb Shahi Tombs', subtitle: 'A royal necropolis in the granite landscape',
    coordinates: [78.3964, 17.3948], visibleFrom: 1543, dateLabel: 'Earliest royal tomb c.1543 · phased complex',
    model: 'tombs', category: 'Sacred',
    description: 'North of Golconda, domed mausoleums on raised platforms form the dynastic burial landscape of the Qutb Shahi rulers. The complex developed across generations rather than appearing as a finished ensemble at one date.',
    caveat: 'The grouping represents the architectural family, not a dated inventory of every tomb. The early-era complex is deliberately smaller.',
    sources: ['unesco'],
  },
  {
    id: 'purana-pul', name: 'Purana Pul', subtitle: 'A crossing older than Hyderabad',
    coordinates: [78.4594, 17.3711], visibleFrom: 1578, dateLabel: 'c.1578 · Ibrahim Quli Qutb Shah',
    model: 'bridge', category: 'Infrastructure',
    description: 'The old bridge over the Musi predates the founding of Hyderabad. It connects the story of Golconda to the river corridor in which the new capital would take shape.',
    caveat: 'The arched bridge is schematic. Its exact historic riverbanks, approaches and later alterations are not reconstructed.',
    sources: ['bridge'],
  },
  {
    id: 'charminar', name: 'Charminar', subtitle: 'The founding city’s four-sided heart',
    coordinates: [78.4747, 17.3616], visibleFrom: 1591, dateLabel: '1591 · Muhammad Quli Qutb Shah',
    model: 'charminar', category: 'Civic',
    description: 'Charminar stands at the symbolic centre of the city founded by Muhammad Quli Qutb Shah. Four soaring minarets and four monumental arches give it a form tied to the crossroads around it.',
    caveat: 'The monument’s form is documented; the surrounding founding-era blocks and bazaar streets shown here are interpretive. Popular origin stories are not treated as established fact.',
    sources: ['unesco', 'charminar'],
  },
  {
    id: 'mecca-masjid', name: 'Mecca Masjid', subtitle: 'A monumental prayer hall across generations',
    coordinates: [78.4736, 17.3604], visibleFrom: 1694, dateLabel: 'Begun c.1614–17 · completed c.1693–94',
    model: 'mosque', category: 'Sacred',
    description: 'Started under the Qutb Shahis and completed during Mughal rule, the mosque embodies a long construction history beside Charminar. Its great prayer hall and courtyard anchor the old city.',
    caveat: 'Telangana Tourism dates construction to 1614–1693; other accounts give 1617 and 1694. The conservative 1694 gate means the completed miniature is absent in 1687, although construction was under way.',
    sources: ['mosque'],
  },
  {
    id: 'chowmahalla', name: 'Chowmahalla Palace', subtitle: 'Ceremony, courtyards and the Asaf Jahi court',
    coordinates: [78.4717, 17.3578], visibleFrom: 1869, dateLabel: 'Begun 1750 · major completion 1857–69',
    model: 'palace', category: 'Palace',
    description: 'The palace complex became a ceremonial centre of the Nizams. Courtyards, halls and distinct palace ranges tell the story of a court whose buildings accumulated over several reigns.',
    caveat: 'The complete composite palace is shown only from the late 19th century. This does not imply that the site was empty in 1763.',
    sources: ['chowmahalla'],
  },
  {
    id: 'residency', name: 'Koti Residency', subtitle: 'A Palladian landmark on the north bank',
    coordinates: [78.4866, 17.3848], visibleFrom: 1805, dateLabel: 'c.1797–1805 · British Residency',
    model: 'residency', category: 'Civic',
    description: 'The Residency’s classical columns and formal facade mark the institutional landscape that grew on the northern side of the Musi. Its later life as an educational campus adds another layer to the city.',
    caveat: 'This is a simplified exterior, without a reconstruction of the historic compound, later campus, or interiors.',
    sources: ['residency'],
  },
  {
    id: 'falaknuma', name: 'Falaknuma Palace', subtitle: 'An elevated panorama above the old city',
    coordinates: [78.4675, 17.3315], visibleFrom: 1893, dateLabel: '1884–1893 · late 19th-century palace',
    model: 'palace', category: 'Palace',
    description: 'Built on a hill south of the old city, Falaknuma brings European-influenced palace architecture into a Deccani setting. Its elevated position gives a different perspective on the city’s expansion.',
    caveat: 'The facade and wings are original stylized geometry. Room layouts, decorative surfaces and a measured terrain survey are not included.',
    sources: ['falaknuma'],
  },
  {
    id: 'high-court', name: 'Telangana High Court', subtitle: 'An institutional landmark beside the Musi',
    coordinates: [78.4720, 17.3692], visibleFrom: 1920, dateLabel: 'Built c.1915–19 · inaugurated 1920',
    model: 'court', category: 'Civic',
    description: 'The domed High Court building is part of the early 20th-century transformation of the riverfront. Its institutional silhouette helps locate the Musi between the old city and the expanding northern districts.',
    caveat: 'Court establishment in 1919 and the building’s inauguration in 1920 are different milestones. The completed building is deliberately absent from the 1908 flood chapter.',
    sources: ['court', 'court-building', 'flood'],
  },
  {
    id: 'osmania', name: 'Osmania Arts College', subtitle: 'A university gives the city a new horizon',
    coordinates: [78.5266, 17.4190], visibleFrom: 1939, dateLabel: '1938–39 · Arts College building',
    model: 'university', category: 'Civic',
    description: 'Osmania University was founded in 1917. Its own history dates the Arts College inauguration to 1938, while other accounts give 1939. The campus represents educational expansion beyond the old urban core.',
    caveat: 'The 1938/1939 discrepancy is retained rather than silently resolved; the model uses a conservative 1939 gate. It depicts an interpreted Arts College exterior, not the entire campus. The coordinate is an approximate campus anchor.',
    sources: ['osmania', 'osmania-position'],
  },
  {
    id: 'buddha', name: 'Hussain Sagar Buddha', subtitle: 'A modern landmark on an older lake',
    coordinates: [78.4750, 17.4156], visibleFrom: 1992, dateLabel: '1992 · installed on the lake',
    model: 'buddha', category: 'Sacred',
    description: 'The Buddha statue is a late 20th-century addition to Hussain Sagar. The lake itself dates to 1562–63, making this a clear example of two very different historical layers occupying one landscape.',
    caveat: 'The figure is a respectful, abstract procedural silhouette. The lake outline is an approximate orientation guide, not its shoreline in any particular year.',
    sources: ['lake'],
  },
  {
    id: 'cyber-towers', name: 'Cyber Towers', subtitle: 'The western city turns toward information technology',
    coordinates: [78.3814, 17.4504], visibleFrom: 1998, dateLabel: '1998 · HITEC City milestone',
    model: 'cyber', category: 'Technology',
    description: 'Cyber Towers is a visual marker of the late 1990s development of HITEC City. The westward technology corridor adds another centre to a city that had already shifted from fort to old city to northern districts.',
    caveat: 'The 1998 opening is supported here by a secondary property directory, not a first-party inauguration record. Confidence is lower than the UNESCO-backed monuments. The sparse western context does not imply that today’s skyline existed in 1998.',
    sources: ['hitec'],
  },
]

export const ERAS: Era[] = [
  {
    year: 1518, label: 'Golconda', chapter: 'Qutb Shahi beginnings', title: 'Before Hyderabad.',
    description: 'Begin among the granite hills at Golconda, as the Qutb Shahi kingdom emerges. The city we now call Hyderabad has not yet been founded. The story begins with a fortified landscape, not Charminar.',
    changes: ['Golconda is the political anchor of this chapter.', 'The future Hyderabad plain is shown sparsely, not as a mapped 1518 settlement survey.', 'Hussain Sagar, dating to 1562–63, is deliberately absent.'],
    sources: ['unesco', 'history'], density: .18, districts: ['golconda'], tour: ['golconda'],
  },
  {
    year: 1591, label: 'A new capital', chapter: 'Muhammad Quli Qutb Shah', title: 'A city is imagined.',
    description: 'Hyderabad is founded east of Golconda, with Charminar at its heart. The Musi, an older bridge and the royal landscape connect a new capital to the Deccan city that came before it.',
    changes: ['Charminar enters the city’s skyline.', 'The new urban focus lies south of the Musi.', 'Golconda and the dynastic tombs remain part of the wider landscape.'],
    sources: ['unesco', 'charminar', 'bridge'], density: .35, districts: ['golconda', 'old-city'], tour: ['charminar', 'purana-pul', 'golconda', 'tombs'],
  },
  {
    year: 1687, label: 'Empire shifts', chapter: 'Mughal conquest', title: 'The kingdom changes.',
    description: 'The fall of Golconda to Aurangzeb ends Qutb Shahi sovereignty. The city’s monumental framework remains, even as its political world changes. This chapter is a transition in rule, not a claim that the city was rebuilt overnight.',
    changes: ['Golconda falls after a Mughal siege.', 'The Qutb Shahi monuments outlast the dynasty.', 'Mecca Masjid is still unfinished; the completed model appears in later chapters.'],
    sources: ['unesco', 'history', 'mosque'], density: .44, districts: ['golconda', 'old-city'], tour: ['golconda', 'tombs', 'charminar'],
  },
  {
    year: 1763, label: 'The Nizams', chapter: 'Asaf Jahi capital', title: 'A court returns.',
    description: 'Under Nizam Ali Khan, the Asaf Jahi capital returns from Aurangabad to Hyderabad. The transfer is commonly dated to 1763, but a Telangana government account gives 1769. This chapter represents a mid-century transition, not a precisely surveyed single year.',
    changes: ['The return of the court is a historical process; the exact date varies by source.', 'The now-completed Mecca Masjid anchors the old-city ensemble.', 'The later, complete Chowmahalla palace is withheld; its earlier site was not empty.'],
    sources: ['history', 'capital', 'chowmahalla', 'mosque'], density: .55, districts: ['golconda', 'old-city', 'north-bank'], tour: ['charminar', 'mecca-masjid', 'purana-pul'],
  },
  {
    year: 1908, label: 'The great flood', chapter: 'A watershed year', title: 'The river changes everything.',
    description: 'The catastrophic Musi flood of September 1908 exposes the city’s vulnerability. It becomes a turning point in the subsequent history of water management and civic rebuilding. The map does not speculate about the inundated footprint.',
    changes: ['The flood is a dated event, not a simulated flood overlay.', 'The north-bank Residency and southern palaces show an expanded city.', 'The High Court and Osmania Arts College belong to later decades.'],
    sources: ['flood', 'residency', 'court'], density: .7, districts: ['golconda', 'old-city', 'north-bank', 'secunderabad'], tour: ['purana-pul', 'residency', 'chowmahalla', 'falaknuma'],
  },
  {
    year: 1948, label: 'A new chapter', chapter: 'Integration into India', title: 'A different future.',
    description: 'Following the military operation known as Operation Polo, Hyderabad State is integrated into the Indian Union in September 1948. The city now includes major civic and educational institutions alongside its enduring old core.',
    changes: ['Integration on 17 September marks a new political chapter, not an overnight architectural transformation.', 'The High Court, inaugurated in 1920, is now part of the riverfront.', 'Osmania Arts College marks a growing institutional landscape.'],
    sources: ['court', 'court-building', 'osmania'], density: .85, districts: ['golconda', 'old-city', 'north-bank', 'secunderabad'], tour: ['high-court', 'osmania', 'charminar'],
  },
  {
    year: 1998, label: 'Cyberabad', chapter: 'The western turn', title: 'Another centre emerges.',
    description: 'The opening of Cyber Towers marks a milestone in HITEC City’s development. Follow the map west to see the idea of a technology-led district, while the lake and old city continue to anchor Hyderabad’s identity.',
    changes: ['Cyber Towers appears in the western corridor.', 'The Buddha statue is a new layer on 16th-century Hussain Sagar.', 'This is an emerging district, not the complete present-day skyline.'],
    sources: ['hitec', 'lake'], density: 1, districts: ['golconda', 'old-city', 'north-bank', 'secunderabad', 'west'], tour: ['cyber-towers', 'buddha', 'charminar'],
  },
  {
    year: 2025, label: 'Many Hyderabads', chapter: 'Contemporary metropolis', title: 'The past is still here.',
    description: 'The contemporary city has many centres: Golconda’s granite, the old city’s bazaars, the lake, university districts and the western technology corridor. Move between them and notice how history survives within an expanding metropolis.',
    changes: ['The western skyline becomes a stronger visual layer.', 'A roughly 48 × 50 km envelope connects 25 interpreted neighbourhood zones.', 'Buildings and roads remain interpretive, not a live cadastral map or the HMDA boundary.'],
    sources: ['hmda', 'unesco', 'hitec'], density: 1.4, districts: ['golconda', 'old-city', 'north-bank', 'secunderabad', 'west'], tour: ['cyber-towers', 'osmania', 'buddha', 'charminar', 'golconda'],
  },
]
